/**
 * Application revision number + changelog.
 * Incremented on every push to GitHub.
 * Minor bumps (1.1 -> 1.2) on regular pushes.
 * Major bumps (1.x -> 2.0) on request for larger changes.
 */
export const APP_VERSION = '1.26';

/** Changelog — newest first. Keep entries short. */
export const CHANGELOG = [
  {
    version: '1.26',
    date: '2026-04-25',
    time: '13:00',
    author: 'Dan Belliveau',
    changes: [
      'AnalogSensor (probe) is no longer a state-logic action subject. The "Check In Range" / "Read Value" operation menu is gone — those operations conflated CTA (condition-to-advance) with outcome, which is the same thing every other node already gets right (Extend\'s CTA is "extend done", ServoMove\'s CTA is "axis at target", etc.). Probes now act like sensors: declare the device, declare its setpoints, and reference each setpoint via a Verify-mode Decision node against the per-setpoint `RC.InPos` BOOL bit. Continuous AOI_RangeCheck monitoring in R03 is unchanged — it still emits one rung per declared setpoint regardless of whether any state references it.',
      'Verify-input picker drops the probe raw-value RANGE entry. The only reason to reach into a probe from a verify is to assert that a named setpoint is in range — exposing the raw `Scaled` value as a free-form RANGE input was confusing and never matched real workflow ("you would never just read the value to read it for fun"). Each declared setpoint still appears as a BOOL `RC.InPos` chip in the Analog Sensors group.',
      'Decision popup mode buttons are now LIVE. Clicking Wait / Decide / Verify in the popup immediately commits `nodeMode` (and the matching default `exitCount`) to the underlying node or `_decision` row, so the node recolors instantly — blue for Wait, purple for Decide, orange for Verify — instead of staying on the previous color until Done is clicked. The rest of the popup state (signal pick, condition, PT config) remains buffered until commit, so an in-progress edit isn\'t partially saved.',
      'Migration on hydration: any legacy `CheckRange` / `VerifyValue` / `ReadValue` action row on an AnalogSensor is rewritten in place to a `_decision` row with `nodeMode: \'verify\'`, sensor refs pointing at `{name}{setpointName}RC.InPos`, and any tracking-field write carried over to the new row\'s `ptEnabled` / `ptFieldId` / `ptPassValue` config. Stamped `migratedToVerify: true` so it doesn\'t re-run. Action `id` is preserved.',
      'L5X exporter: the AnalogSensor R02 verify branch is removed. Verify nodes (`_decision` rows or standalone DecisionNodes) compile their own XIC/XIO conditions through the generic verify-condition path against the same `{name}{setpointName}RC.InPos` tags. R03 continuous monitoring is untouched.',
      'StateNode subject picker filters out AnalogSensor devices. The "Wait / Decision / Verify" entry in the same picker is unchanged and is the canonical way to bring a probe setpoint into a state machine\'s flow.',
      'Build verified clean (vite v6.4.1, 239 modules, same warnings as 1.25).',
    ],
  },
  {
    version: '1.25',
    date: '2026-04-25',
    time: '12:00',
    author: 'Dan Belliveau',
    changes: [
      'Dev-experience: navigation infrastructure for AI-assisted sessions. The three biggest files in the repo (`src/store/useDiagramStore.js` ~4,900 lines, `src/lib/l5xExporter.js` ~5,300 lines, `src/components/nodes/StateNode.jsx` ~3,900 lines) cost 30-90 seconds each to read in full and burn huge context. They now have a TABLE OF CONTENTS at the very top mapping every section to its line range, so an agent can `Read limit:80` the ToC, then jump straight to the section it needs with `offset`/`limit` instead of reading the whole file.',
      'New `src/WHERE.md`: project-wide "phone book" mapping common tasks → file paths, with grep hints for finding the right section inside the big files. Sessions should read this FIRST before probing the codebase. Covers: adding/editing operations, new node types, edge routing, decision/wait/verify nodes, L5X export routines, new device types, project actions, standards library, signals, part tracking, modals, undo/redo, selection.',
      'New per-folder CLAUDE.md docs: `src/store/CLAUDE.md` (Zustand patterns + atomic helpers), `src/lib/CLAUDE.md` (no-React rule + L5X routine line-number map), `src/components/CLAUDE.md` (handle rules + StateNode component map). Each is intentionally short (~40 lines) — they call out folder-specific gotchas and point at WHERE.md for the global map.',
      'Root CLAUDE.md gets a new §0 "WORKING IN THIS REPO — READ FIRST" that lists the three big files, points at their ToCs and at WHERE.md, and prescribes the 4-step navigation playbook (WHERE.md → ToC → Grep → Read narrow window) plus when to spawn the Explore sub-agent. No code changes — pure docs/header insertion.',
      'No runtime impact. Build verified clean (vite v6.4.1, 239 modules, same warnings as 1.24.22 about chunk size). Same bundle output. This is preparation for the planned aggressive file-breakup (slices for the store, per-routine files for the exporter, per-component files for StateNode) — but each file gains a "Planned restructure" pointer so the navigation aids stay correct as the splits land.',
    ],
  },
  {
    version: '1.24.22',
    date: '2026-04-24',
    time: '15:30',
    author: 'Dan Belliveau',
    changes: [
      'Servo L5X fixes after engineer review (Jason Perry, 2026-04-24): "errors importing the servo axis data types" + "leftover servo code in the state logic routine" — both addressed.',
      'R03_StateLogic no longer emits servo motion rungs. Position Select / MAM Execute / AOI_RangeCheck now live EXCLUSIVELY in R04/R05 per-axis routines (SDC Guide §15.4). The duplicate emission in R03 was causing Studio 5000 import conflicts and leaving stale logic the engineer had to hand-clean after every import.',
      'AXIS_CIP_DRIVE controller tags now carry the full Rockwell default AxisParameters block (~85 attributes, copied verbatim from engineer reference S05_ServoPNP.L5X — only MotionModule and AxisID vary per axis). Previously emitting ~30 attributes, which Studio 5000 rejected as an incomplete axis data type. Import errors should be gone.',
      'Smoke test confirms: R03 has 0 MAM / 0 RangeCheck, R04/R05 per axis has 2 MAM / 2 RangeCheck, MotorCatalogNumber + CIPAxisExceptionAction markers present. Output is ~163 KB for the 2-axis PNP test case (up from ~147 KB pre-fix).',
    ],
  },
  {
    version: '1.24.20',
    date: '2026-04-24',
    time: '14:30',
    author: 'Dan Belliveau',
    changes: [
      'L5X generator rewrite merged in from the loving-sammet worktree — the 1.24.2-era generator fix that got stranded when 1.24.3+ signal/multi-stage work went forward on main is now reunited with the current UI. Layered output architecture (L1 Infrastructure / L2 Station-type template / L3 Per-device / L4 Flowchart-compiled / L5 Always-on boilerplate) is live in `l5xExporter.js`, with gating on declared project state rather than reference-file splicing.',
      'Tag naming corrected to SDC PLC Standardization Guide Rev 1 full-word convention: `q_Extend{name}` / `q_Retract{name}` (was `q_Ext` / `q_Ret`), `i_{name}Extended` / `i_{name}Retracted` (was `i_{name}Ext` / `i_{name}Ret`), `{name}ExtendDelay` / `{name}RetractDelay` (was `{name}ExtDelay`), `{name}RC.InPos` (was `{name}RC.In_Range`). Updated `tagNaming.js`, `conditionBuilder.js`, `availableInputs.js`, `deviceTypes.js`, plus downstream verify-text builders in `StateNode.jsx` and help text in `AddDeviceModal.jsx`.',
      'Servo architecture: controller-scope `a{NN}_S{station}{name}` AXIS_CIP_DRIVE tag (e.g., `a02_S01PNPXAxis`, not the stripped `a02_PNPXAxis` bug from the splice), program-scope `iq_{name}` InOut param aliased to the controller tag, `HMI_{name}` ServoOverall UDT per axis, full motion-instruction complement (MSO/MSF/MAFR/MASR/MAJ/MAS_Jog/MAH+AOI_TorqueHome/MAM_Auto), and position arrays with STABLE indices that never reshuffle on delete.',
      'Reserved state skeleton enforced: DFS no longer emits flowchart numbers into 99 (lockout), 100–127 (init block), or 1–3 (reserved future). Station-type templates (first: `SDCStandardPNP`) own 100→...→127; flowchart starts after the init-complete bridge. Fault state stays pinned at 127, recovery `Cycle Complete` stays pinned at 124.',
      'R01 boilerplate: HMI_Toggle fixed bit map (.0 Lockout / .1 DryRun / .2 SS), SS_OK derivation with StepAdvance pulse, HMI_Momentary auto-clear rungs, 1-sensor pneumatic invert, AOI_Debounce calls for DigitalSensor part-present devices (NOT for pneumatic extend/retract — those are already state-conditioned).',
      'CLAUDE.md §15 added: "SDC PLC Standards (Generator Rules)" — authoritative layered architecture, tag naming, position stability, servo architecture, reserved state numbers, SDCStandardPNP init template, R01 boilerplate, AOI_Debounce scope rules, 2-solenoid gripper default, R20 alarms, and a "what NOT to do" list (no splicing from reference L5X, no stripped station prefixes, no flowchart numbers in reserved ranges). This is now the source of truth for the generator.',
      'Port in detail: 5 lib files copied wholesale from loving-sammet (`l5xExporter.js`, `tagNaming.js`, `conditionBuilder.js`, `availableInputs.js`, `deviceTypes.js`) — no overlap with main\'s 1.24.19 signal/multi-stage UI work, so merge was surgical. Smoke-test scripts (`scripts/dump-export.mjs`, `scripts/smoke-export.mjs`) also ported for exporter verification. `.gitignore` extended to exclude confidential PLC guide material and smoke-test output.',
      'Known follow-up: project-level signals (including 1.24.17\'s latched signals) are not yet wired into L5X tag/rung emission — the data model is in place, but the generator currently emits legacy `smOutputs` only. Queued for 1.24.21+.',
    ],
  },
  {
    version: '1.24.19',
    date: '2026-04-24',
    time: '13:20',
    author: 'Dan Belliveau',
    changes: [
      'Decide rows: the internal signal recipe line (e.g., "SDC_Servo_PNP is in State 7") is no longer rendered under the signal name. A Decide is a snapshot-and-branch — the reader of the row cares about "I\'m branching on Part_Gripped", not the chain of conditions that determines Part_Gripped\'s bit. Recipe is still reachable via hover tooltip on the signal name ("Part_Gripped — TRUE when SDC_Servo_PNP is in State 7") and via the edit popup.',
      'Decide rows on project-level signals now render a broadcast "Signal" icon next to the signal name, matching the visual grammar of every other row (every row leads with a device/signal icon). New SignalIcon glyph added to DeviceIcons.jsx (dot-with-radiating-arcs) + registered as a regular DeviceIcon type so other surfaces can reuse it.',
      'Fallback order for the Decide / Verify / Wait row icon is: vision job → live device tag → sensor ref → project signal (new). Rows that previously rendered iconless now pick up the Signal glyph.',
    ],
  },
  {
    version: '1.24.18',
    date: '2026-04-24',
    time: '13:00',
    author: 'Dan Belliveau',
    changes: [
      'Fix: signal chips on state nodes now render INSIDE `state-node__body` instead of as siblings after it. SVG-shaped nodes (pentagon / hexagon / octagon / decagon / etc.) make `state-node__body` sit at `z-index: 1` above the SVG `.state-node__shape-bg` — siblings fell back to the default stacking order and ended up visually clipped behind the shape. This is why 1.24.17 rendered the red "Part_Gripped OFF" chip as a sliver peeking from behind a pentagon on state 19. Chips (and the legacy-output row right above them) are now inside the body and paint cleanly on every shape.',
      'Fix: PtBadge no longer renders the blue ⚑ flag for project-level state signals. 1.24.17 added green/red chips for signals but left PtBadge\'s signal path intact, so ON-side nodes (state 7 in the reported bug) displayed BOTH the corner ⚑ and the inline chip — same information twice, in conflicting colors. PtBadge is now PT-annotations + legacy `smOutputs` only. Project signals live exclusively in the chip row and the sidebar latch indicator.',
      'Housekeeping: dropped the dead `REACHED_MODE_LABELS` constant from PtBadge.jsx (it was only referenced by the signal popup row we just deleted).',
    ],
  },
  {
    version: '1.24.17',
    date: '2026-04-24',
    time: '12:35',
    author: 'Dan Belliveau',
    changes: [
      'Signals: opt-in OFF condition. Every signal still has a top condition that turns it ON (pure OTE — unchanged). A new checkbox "Also define an OFF condition" reveals a second block of the same type (SM State / Position / Condition). When present, the signal becomes a SET/RESET latch — OTL on ON-fire, OTU on OFF-fire — so sequence flags like `Part_Gripped` can latch at state 7 and release at state 15 without a separate branch or node. Backward compatible: `offCondition: null` means today\'s behavior exactly.',
      'Sidebar signal list: every signal row now shows a latch indicator next to the type badge. Blue filled dot = pure computed (OTE). Split green/red circle = latched (OTL + OTU). Hover for a tooltip summarizing the semantics.',
      'State nodes: inline colored chips appear on the state the signal\'s ON condition references (green chip "SignalName ON" for latched, blue chip "SignalName" for pure computed) AND on the state its OFF condition references (red chip "SignalName OFF"). Gives at-a-glance visibility into which states fire which signals without opening the signal editor. Only SM-State signals render chips — position/condition signals don\'t pin to a specific node.',
      'L5X export wiring for latched signals is queued as a follow-up — the data model is in place but project signals don\'t yet emit controller tags/rungs regardless of latch type.',
    ],
  },
  {
    version: '1.24.16',
    date: '2026-04-24',
    time: '12:05',
    author: 'Dan Belliveau',
    changes: [
      'Recovery "Cycle Complete" now ALWAYS numbers to step 124 regardless of how the node was created. Engineers call recovery sequences "initialize"; in the SDC PLC standard, 124 is the reserved initialize/recovery-complete step. Previously only nodes with `data.isComplete: true` were pinned — nodes built before the recovery picker wired up that flag (label = "Cycle Complete" but no flag) were getting sequential numbers like 109.',
      'Two-pronged fix: (1) `computeStateNumbers` now treats a node as the cycle-complete terminal when `data.isComplete === true` OR `data.label === "Cycle Complete"` (case-insensitive). (2) Project hydration auto-heals legacy recovery nodes: any state node labeled "Cycle Complete" in a recovery sequence without the flag gets `isComplete: true` set on load, so PT writes, L5X export, and styling all stay consistent with numbering.',
    ],
  },
  {
    version: '1.24.15',
    date: '2026-04-24',
    time: '11:40',
    author: 'Dan Belliveau',
    changes: [
      'HOTFIX: "Wait / Decision / Verify" crashed the app with `ReferenceError: isSensor is not defined`. The v1.24.13 rewrite of the Step-2 IIFE removed the `isSensor`/`isRange`/`isVerify`/`isVision` locals that deeper JSX branches (sensor condition config, range setpoint picker) still reference. Re-added them inside the IIFE alongside the new `vocab` helper.',
    ],
  },
  {
    version: '1.24.14',
    date: '2026-04-24',
    time: '11:25',
    author: 'Dan Belliveau',
    changes: [
      '`syncDecisionExitLabels` no longer gates purely on `exitLabelsCustomized === true` — that flag is sticky across saves and stops legacy records from ever being refreshed. Now also checks whether the current labels form a generic-default pair (Pass/Fail, True/False, On/Off, Off/On, InRange/OutOfRange); if they do, overwrites with fresh values from `computeExitLabels` regardless of the flag.',
      'Standalone DecisionNode component: destructured `exit1Label`/`exit2Label` defaults are now vision-aware (Pass/Fail only for `signalType === "visionJob"`, On/Off otherwise).',
    ],
  },
  {
    version: '1.24.13',
    date: '2026-04-24',
    time: '11:10',
    author: 'Dan Belliveau',
    changes: [
      'Redesign: branch-label vocabulary is now PURELY a function of the CONDITION, never the mode. Pass/Fail appears ONLY for vision jobs (which have named pass/fail outcomes). Verify and Decide modes use the condition\'s OWN vocabulary: On/Off for binary conditions (sensor, signal, state, condition, partTracking, partResult), InRange/OutOfRange for ranges. There is no "True/False" anywhere anymore — Decide on a binary is still On/Off. Rationale: Verify asserts "is this condition true?"; Decide branches on the same boolean — neither creates a Pass/Fail concept.',
      'Popup button labels in Step 2 ("1 Single exit — …", "2 Branch … / …") now flow from `conditions[0]` via a single local `vocab` helper. Old code had a tangled switch that produced "True" for wait+signal, "Pass" for verify+signal, etc. — all of those violated the new rule.',
      'DecisionNode `derivePrimary` rewritten to the same rule (vision-only → Pass/Fail; everything else → On/Off or InRange/OutOfRange). `computeExitLabels` (edgeRouting.js) matched so canvas edge labels stay in sync with popup inputs.',
      'handlePTPick no longer sets Pass/Fail as the default Part Tracking branch labels — PT is binary, so it now seeds On/Off (or InRange/OutOfRange for real-typed PT fields).',
      'Part Tracking "Pass writes / Fail writes" column headers in the popup are now "{exit1Label} writes / {exit2Label} writes" — e.g. "On writes SUCCESS" for a binary verify. Stops the UI from saying Pass/Fail when the actual branches are On/Off.',
      'Useless useState fallback `exit1Label ?? \'Pass\'` swapped to a vision-aware fallback (Pass/Fail only if the saved `signalType` is visionJob; On/Off otherwise). The v1.24.12 effect still auto-refreshes on mount, but the placeholder now won\'t flash Pass/Fail for one frame on a binary popup.',
    ],
  },
  {
    version: '1.24.12',
    date: '2026-04-24',
    time: '10:45',
    author: 'Dan Belliveau',
    changes: [
      'Fix: DecisionEditPopup Left/Right exit inputs ACTUALLY refresh to the current-vocabulary defaults now — v1.24.11 gated on the `exitLabelsCustomized` flag, but that flag gets sticky-true across saves and stops the refresh from ever firing on legacy records. v1.24.12 drops the flag gate and instead detects whether the current labels are a GENERIC DEFAULT PAIR (Pass/Fail, True/False, On/Off, Off/On, InRange/OutOfRange). If so → overwrite with `derivePrimary(conditions[0])` output. A user-typed custom label like "Gripped"/"Slipped" won\'t match any default pair, so real customizations stay put. Pre-v1.24.10 "Pass/Fail on a binary signal" records now correct themselves on first popup open.',
    ],
  },
  {
    version: '1.24.11',
    date: '2026-04-24',
    time: '10:35',
    author: 'Dan Belliveau',
    changes: [
      'Fix (superseded by 1.24.12): DecisionEditPopup Left/Right exit inputs now show the correct default labels for the current condition vocabulary on open. First attempt gated on `exitLabelsCustomized` — but that flag was sticky-true on legacy records so the refresh never fired. See 1.24.12 for the actual fix.',
    ],
  },
  {
    version: '1.24.10',
    date: '2026-04-24',
    time: '10:20',
    author: 'Dan Belliveau',
    changes: [
      'Fix: embedded decision on a RECOVERY tab no longer silently fails to create branches. The "is this the last row?" check in `DecisionEditPopup.handleDone` now searches both `sm.nodes` and `sm.recoverySeqs[*].nodes` — before, recovery-tab parent states returned undefined and skipped branch creation entirely.',
      'Branch labels now default to the CONDITION vocabulary instead of generic True/False. Verifying a signal "on" → branches default to On/Off (not Pass/Fail). Applies to sensor, signal, state, condition, and partTracking signal types — all binary conditions share the same vocabulary. Range stays InRange/OutOfRange; vision jobs stay Pass/Fail (they have named outcomes). Verify mode additionally flips so exit1 = picked polarity (Verify Off → exit1=Off).',
      'Synchronized the label derivation across three sites: `handleSignalPick` (initial set), `derivePrimary` (re-derive at save), and `computeExitLabels` (canvas render + `syncDecisionExitLabels`). All three now agree.',
    ],
  },
  {
    version: '1.24.9',
    date: '2026-04-24',
    time: '10:00',
    author: 'Dan Belliveau',
    changes: [
      'Fix: picking "Branch Pass/Fail" in a VERIFY decision (standalone or embedded) was silently reverting to 1 exit on Done — `finalExitCount` clamped verify mode to 1 regardless of what the user selected. The "2 branches" button is visible for verify (pass=continue, fail=fault/recovery is a legitimate pattern), so the clamp was wrong. Removed. Embedded-verify + last-row + 2 exits now correctly triggers `addDecisionBranches` and spawns Pass_X / Fail_X nodes below the state with the right side handles.',
    ],
  },
  {
    version: '1.24.8',
    date: '2026-04-24',
    time: '09:45',
    author: 'Dan Belliveau',
    changes: [
      'Embedded decision rows now look and branch EXACTLY like a standalone DecisionNode. Extracted a shared `<DecisionBody>` component with full derivation logic (mode → fill/border colors, live device/signal resolution, op badge label + color, verify-text subtitle, retry/PT badges, On/Off switcher) and used it for BOTH the standalone DecisionNode body and the embedded `_decision` ActionRow in StateNode. Wait = blue, Decide = purple, Verify = orange — all the same visual grammar as standalone.',
      'When an embedded decision is the LAST row in a state AND has 2 exits, the parent state automatically grows `exit-pass` / `exit-fail` side handles (same pattern as vision-inspect side-exit states) and spawns Pass_X / Fail_X branch nodes below via `addDecisionBranches`. Retry branch is added too when retry is enabled. Non-last-row embedded decisions stay single-exit (they gate the next row via their advanceCondition).',
      '`addDecisionBranches` refined: early-return "branches already exist" path now only fires when real exit-pass/exit-fail edges are present, not any outgoing edge. Reusable bottom-handle edges are retargeted to `exit-pass` when creating branches, so adding a verify to an existing state with a "next state" edge preserves the downstream connection as the pass branch and spawns the fail branch below-right.',
      '`OnOffSwitcher` + `DecisionBody` now accept an `onUpdate(patch)` callback. Embedded rows route this to `updateAction(smId, parentNodeId, actionId, patch)` so On/Off toggles persist into the parent state\'s action array instead of trying to overwrite node-level data.',
    ],
  },
  {
    version: '1.24.7',
    date: '2026-04-24',
    time: '09:15',
    author: 'Dan Belliveau',
    changes: [
      'Embedded decision row editor now uses the EXACT SAME popup as a standalone DecisionNode — no homemade config panel. `DecisionEditPopup` is exported from DecisionNode.jsx and takes an optional `saveTarget="action"` + `actionId` to route the save through `updateAction` on the embedded row instead of `updateNodeData` + branch-node creation. All sections (vision jobs, signals, sensors, part tracking, conditions, retry, PT write, multi-condition AND/OR, Left/Right label inputs, On/Off presets) work identically on an embedded row.',
    ],
  },
  {
    version: '1.24.6',
    date: '2026-04-24',
    time: '09:00',
    author: 'Dan Belliveau',
    changes: [
      '"Wait / Decision / Verify" from the Select Subject picker now adds an EMBEDDED action row inside the current state — mirrors how adding a second device action works. No more separate DecisionNode below. The row lives alongside pneumatic/servo/PT rows and can have its own `advanceCondition` chip ("then …") gating the next row.',
      'New action schema: `deviceId: \'_decision\'` with `nodeMode` ∈ {wait | decide | verify}, `signalId`, `signalName`, `signalSource`, `signalType`, `conditionType`, `exitCount`, `exit1Label`, `exit2Label`. ActionRow has a rendering branch for this: big-bold signalSource (device/SM), small subtitle signalName (job/signal), mode pill (Wait=blue, Decide=purple, Verify=orange), Verify On/Off colored chip, Pass/Fail exit chips for 2-branch mode.',
      'Standalone DecisionNodes still exist and can be dragged in from the canvas add-menu — this change is only about what happens when you hit "+" on an existing state.',
    ],
  },
  {
    version: '1.24.5',
    date: '2026-04-24',
    time: '08:15',
    author: 'Dan Belliveau',
    changes: [
      'Per-row "advance condition" on state action rows — each action now has a small "then …" chip below it that says when the NEXT row starts: after complete (default) / concurrent / timer (ms + from-start or from-complete) / sensor ON / sensor OFF / servo at position / servo at %. Matches how programmers mentally model multi-action states ("retract Z, then wait 50ms, then fire stamper"). Last row has no chip — its gate IS the edge to the next state (plumbed in a follow-up pass).',
      'Fix: "Wait / Decision / Verify" from a state on the recovery tab was silently closing — `handleSignalPick` was calling main-diagram `addDecisionNode` + `addEdge` even when the parent state lived in a recovery sequence, so the new decision node landed in `sm.nodes` (invisible on the recovery tab) instead of the sequence. Now routes through `addRecoveryNode`/`addRecoveryEdge`. `addRecoveryNode` extended to accept `type: \'decisionNode\'` + custom `data` for this.',
      'Top-right "+" button on state nodes now opens the Select Subject picker directly — no more intermediate 3-option submenu (Add Action / Add State / Add Decision). The picker already has all those paths as subjects.',
      'Decision node: Canvas live-label render now prefers stored `exit1Label`/`exit2Label` over `computeExitLabels()` defaults, so custom labels typed into Left/Right inputs ("On"/"Off" for a signal-type decision) actually stick on the edge pills. Pairs with the exitLabelsCustomized flag shipped in 1.24.4.',
    ],
  },
  {
    version: '1.24.4',
    date: '2026-04-24',
    time: '07:30',
    author: 'Dan Belliveau',
    changes: [
      'Decision node: custom exit labels are now SACRED. Type "On"/"Off" into the Left/Right exit inputs of a signal-type decision → "On"/"Off" sticks on the branches and in the node data. Was silently reverting to "True"/"False" on Done because `syncDecisionExitLabels` auto-corrected anything that didn\'t match its computed defaults.',
      'Fix at two layers: (1) `handleDone` no longer re-derives exit labels from `primary.exit1/exit2` — uses the input state directly; (2) new `exitLabelsCustomized` flag on the node, set when the user types into Left/Right inputs and cleared when they pick a new condition or preset. `syncDecisionExitLabels` early-returns on customized nodes so nothing clobbers them on render.',
    ],
  },
  {
    version: '1.24.3.1',
    date: '2026-04-23',
    time: '10:45',
    author: 'Dan Belliveau',
    changes: [
      'Recovery tab now behaves identically to the main sequence tab — same signal picker, same decision/verify/wait conversions, same branch creation, same verify routing. Every store mutation that used to hard-code `sm.nodes` / `sm.edges` now routes through a container-agnostic helper so recovery nodes aren\'t silently dropped.',
      'Architectural fix: store functions `addDecisionBranches`, `addDecisionSingleBranch`, `addDecisionRetryBranch`, `addDecisionMultiBranch`, `addVisionBranches`, `addVisionSingleBranch`, `syncDecisionExitLabels`, `findOrCreateVerifyDevice`, `addVerifyCondition`, `removeVerifyCondition`, and `duplicateNode` are now recovery-aware. Was causing silent "click does nothing" failures on recovery decision nodes.',
      'StateNode verify-flow picker (`handleVerifyConditionsDone`, `handleVerifyFinish`, `verify-route` step) now scopes node + edge lookups to whichever container owns the node — loop-back targets on a recovery tab come from that recovery seq, not the main diagram.',
      'Recovery state numbering: Cycle Complete nodes in a recovery sequence are now pinned to step 124 (the initialize / recovery-complete step in the SDC PLC standard). `computeStateNumbers` takes a new `completeStep` option; 124 is skipped in the sequential counter so a busy recovery flow can\'t collide. Inline "Cycle Complete" picker card shows a "Step 124" hint on recovery tabs, matching the Fault "Step 127" hint.',
      '(Local-only label: this landed in parallel with Abhi\'s 1.24.3 installer fix — renumbered to 1.24.3.1 to preserve Abhi\'s version in the changelog while keeping this entry chronologically after it.)',
    ],
  },
  {
    version: '1.24.3',
    date: '2026-04-23',
    time: '09:45',
    author: 'Abhi Kamuju',
    changes: [
      'Fix: NSIS installer now skips failed uninstall and completes a fresh install instead of aborting — resolves "Failed to uninstall old application files: 2" error on auto-update across all machines.',
    ],
  },
  {
    version: '1.24.1',
    date: '2026-04-23',
    time: '08:55',
    author: 'Dan Belliveau',
    changes: [
      'Edit Subject modal for Servo Axis: "Subject Name" is now labelled "Axis Name" (matches how CEs talk about servos). Hint reflects the servo tag conventions (a01_{name}, p_{name}Home, …).',
      'Edit Subject modal for Servo Axis: "PLC Tag Stem" field hidden — servo tag generation is driven entirely by the axis name and fixed SDC conventions, so the stem just duplicates the axis name. Stem still auto-syncs in state under the hood so downstream tag generation is unchanged.',
      'Non-servo devices keep both fields (Subject Name + PLC Tag Stem) — those need the escape hatch when the ME name doesn\'t map cleanly to a PLC identifier.',
    ],
  },
  {
    version: '1.24',
    date: '2026-04-22',
    time: '17:15',
    author: 'Dan Belliveau',
    changes: [
      'Wait node subtitle now names the SPECIFIC tag that advances the step (e.g. "q_MagnetLoadRobotMagnetPickClear = ON") instead of the owning device ("Magnet_Load_Robot = ON") — you were waiting on the robot\'s output bit, not the robot itself.',
      'Subtitle prefers the exact PLC tag when available, falls back to the signal name with the source prefix stripped ("Magnet_Load_Robot MagnetPickClear [3]" → "MagnetPickClear [3]"). Honors Wait Off so OFF waits no longer mis-label as ON.',
      'Single-exit wait edges now render plain gray like any other sequential state-to-state edge — they were rendering green as if they were a pass branch. A wait with one exit isn\'t a decision; every state needs a condition to advance, this is no different.',
      'Existing project data: Canvas render-layer strip of stale colored-branch styling on `exit-single` edges — no data migration needed.',
      'New single-exit edges created by addDecisionSingleBranch + ClampServoIndex template + onConnect now persist as plain sequential edges (no `isDecisionExit`/`exitColor` flag, no hardcoded green stroke).',
      'Decision node icon now uses the actual device type (Robot / Stamper / ServoAxis / VisionSystem / …) instead of the generic DigitalSensor/AnalogSensor fallback. Robot signals were being masked because they flow through the sensor pick path — `liveDevice?.type` now wins over `isSensor`.',
    ],
  },
  {
    version: '1.23.1',
    date: '2026-04-22',
    time: '21:30',
    author: 'Dan Belliveau',
    changes: [
      'Fix: "Offline" pill stuck on even after a successful boot sync — writeCache fired the change notification before serverReachable flipped to true, so the UI read a stale flag. Flag is now set BEFORE the cache write.',
      'Remove aggressive fs.accessSync W_OK probe on the shared standards path — Windows reports SMB permissions inconsistently and the probe was rejecting writable paths. A successful mkdirSync is enough evidence; real read/write errors now surface cleanly as HTTP 5xx.',
      'New diagnostic endpoint: GET /api/standards/_debug returns the resolved standards dir + file path + entry count. Hit it from the browser when the Offline pill stays on to see which path the server chose.',
      'Standards API: console.info log on successful boot sync (# of standards pulled).',
    ],
  },
  {
    version: '1.23',
    date: '2026-04-22',
    time: '21:00',
    author: 'Dan Belliveau',
    changes: [
      'Standards Library is now TEAM-SHARED — backed by a single JSON file on the N:\\ drive',
      'Save a standard on one machine → every teammate sees it on their next Refresh (or next app launch)',
      'New /api/standards endpoints (GET/POST upsert/DELETE) with auto-backup of the last 5 versions',
      'Electron desktop app defaults standardsDir to N:\\AI Folder\\State Logic Diagrams\\standards with graceful fallback to local AppData if the share is unreachable',
      'localStorage is now only an offline cache — app stays usable without network, syncs when it comes back',
      'StandardsView: "● Shared" / "● Offline" pill shows sync status; new Refresh button pulls latest from server',
      'Import now pushes merged/replaced library to the shared server so everyone sees the imported entries',
      'Removed the public/standards-seed.json fetch-on-first-launch flow — superseded by real sync',
    ],
  },
  {
    version: '1.22',
    date: '2026-04-22',
    time: '16:30',
    author: 'Dan Belliveau',
    changes: [
      'Decision node: "Branch" badge renamed to "Decide" (only on actual decide-mode nodes, not wait nodes with 2 exits)',
      'Wait node branching rule: a single-condition wait can\'t branch — if the condition isn\'t met, the state just doesn\'t advance. "2 branches" button hidden when wait + ≤1 condition',
      'Decide-mode advance-when text now uses LIVE state numbers ("Magnet_PNP has reached State 4") instead of baked "→ Step 3" — never goes stale on renumber',
      'State-signal resolver falls back to matching by state name when the signal lacks a stored node-id (older signals)',
      'addDecisionSingleBranch cleans up excess edges when collapsing a multi-exit node to single-exit — orphaned empty child nodes removed',
      'Mode switcher: switching to wait collapses multi-exit to single when ≤1 condition; verify always collapses to single',
      'Standards library: ships with a seed file (public/standards-seed.json) that auto-imports on first run if localStorage is empty',
      'Standards library: Export / Import JSON buttons in the Standards header — back up or share your library as a file',
    ],
  },
  {
    version: '1.21',
    date: '2026-04-22',
    time: '15:20',
    author: 'Dan Belliveau',
    changes: [
      'Edge clearance: source/target nodes now push their own edge\'s stub-adjacent segments when dragged across them',
      'Dragging a source node DOWN pulls the bottom horizontal with it — no more snap-above-node',
      'Handle-based push direction: bottom-handle source pushes own seg down, side handles push outward, target pushes own seg up',
      'Owner-biased pushes no longer gated by corridor check — force to correct side whenever X ranges overlap',
    ],
  },
  {
    version: '1.20',
    date: '2026-04-22',
    time: '11:00',
    author: 'Dan Belliveau',
    changes: [
      'Standards auto-save — new standards are written to the library immediately on creation; every subsequent edit auto-saves (400ms debounce)',
      'Tab switches / unmounts flush any pending standards save — edits are never lost',
      'Standards-linked tabs show a green "★ Saved" pill in the SM header instead of the star button',
      'Copy button on each library card duplicates a standard to a new editable row with fresh UUIDs (nodes, edges, devices all independent)',
      'Inline rename — double-click a standard name in the library to edit; Enter/blur saves, Esc cancels',
      'Standards grouped by category with uppercase headers and per-category count pills; Uncategorized sorts last',
      'Click anywhere on a library card to open — the redundant Open button is gone',
      'Fix: SM name and description carry into library correctly on open + create',
    ],
  },
  {
    version: '1.19',
    date: '2026-04-22',
    time: '09:30',
    author: 'Dan Belliveau',
    changes: [
      'Design System → Canvas Spacing: editable "Vertical Node Gap" value (default 80px)',
      'Spacing is now a true gap — measured from bottom of one node to top of next, independent of node height',
      'Tall Home nodes no longer squish the visual gap to the next step',
      '+ Add State places new nodes at sourceBottom + gap using React-Flow measured heights',
      'New "Re-space" button in bottom canvas toolbar — applies the configured gap to existing nodes',
      'Re-space honors selection: ≥2 selected → only those nodes; nothing selected → all nodes',
      'Row-aware re-spacing — branch siblings at same Y stay paired after re-spacing',
      'Canvas Spacing input accepts free-typing (clear + retype), commits on valid values or Enter',
    ],
  },
  {
    version: '1.18',
    date: '2026-04-22',
    time: '07:15',
    author: 'Dan Belliveau',
    changes: [
      'Direction arrows now render on every segment longer than 60px — loops and U-bends show flow at each run',
      'Click Wait On / Verify On pill to open an On/Off switcher popup (matches StateNode action-pill UX)',
      'Wait node advance-when text is live — "Magnet_PNP in State 13" / "reached State 13" pulled fresh every render, no stale step references',
      'Signal-based wait pill toggles polarity (Wait On ⇄ Wait Off) instead of being locked on',
      'Inner action-row card tinted to match outer node color — softer contrast on verify/wait nodes',
      'Verify node drops the redundant advance-when row — branch labels already communicate On/Off',
    ],
  },
  {
    version: '1.17',
    date: '2026-04-21',
    time: '16:30',
    author: 'Dan Belliveau',
    changes: [
      'Direction arrows on all edges — subtle chevron mid-last-segment shows flow direction',
      'Unified wait/verify/decide nodes with StateNode ActionRow layout: [icon] [subject bold] [op badge] + advance-when text',
      'Op badge dynamically labels the node: Wait On / Wait Off / Verify On / Verify Off / Branch / Vision / Wait Range / Verify Range',
      'L5X export: SM output tag prefix q_ (was p_) — matches SDC standard for output parameters (non-latching OTE)',
    ],
  },
  {
    version: '1.16.5',
    date: '2026-04-21',
    time: '11:30',
    author: 'Abhi Kamuju',
    changes: [
      'Unsaved-changes guard on app close — matches Word/Excel behaviour',
      'Closing with unsaved work shows: Save / Don\'t Save / Cancel',
      'Save option writes to known file path instantly (no extra dialogs)',
      'Cancel returns to app; Don\'t Save closes immediately',
    ],
  },
  {
    version: '1.16.4',
    date: '2026-04-21',
    time: '11:15',
    author: 'Abhi Kamuju',
    changes: [
      'Load button uses native Electron dialog — remembers the opened file path',
      'Save now writes directly back to the opened file with no dialog and no "replace?" prompt',
      'Completely silent save: open file once, then Ctrl+S or Save button just overwrites instantly',
    ],
  },
  {
    version: '1.16.2',
    date: '2026-04-21',
    time: '10:45',
    author: 'Abhi Kamuju',
    changes: [
      'Fix: JSON save now writes correct file contents in desktop app (was saving 0 KB)',
      'Desktop app uses native Electron save dialog instead of browser File System Access API',
      'Browser (server-app1) continues to use showSaveFilePicker as before',
    ],
  },
  {
    version: '1.16.1',
    date: '2026-04-21',
    time: '10:30',
    author: 'Abhi Kamuju',
    changes: [
      'Fix: version display now correctly shows Rev 1.16.1 (1.16.0 built before version.js was synced)',
      'Save dialog no longer appends _backup to filename — overwrites existing file directly',
    ],
  },
  {
    version: '1.16',
    date: '2026-04-21',
    time: '09:00',
    author: 'Abhi Kamuju',
    changes: [
      'Desktop app: silent auto-update — downloads in background and restarts automatically',
      'No more update dialogs; app checks every 2 minutes and installs with a 5-second countdown',
      'Save dialog remembers last folder used (no more Downloads default)',
      'Toolbar buttons moved below canvas — no longer overlap diagram nodes',
    ],
  },
  {
    version: '1.15',
    date: '2026-04-20',
    changes: [
      'Replaced "S" signal badge with flag icon (⚑) on wait/decision nodes',
      'Avoids letter conflict with PLC "Set" / "State" conventions',
    ],
  },
  {
    version: '1.14',
    date: '2026-04-20',
    time: '11:00',
    author: 'Dan Belliveau',
    changes: [
      'SM title bar redesigned: bigger rounded pill with blue S01 badge',
      'Recovery mode turns the whole title bar red (bg, S01 badge, name text)',
      '+ New Standard button (rounded pill) in Standards Library header',
      'Inline naming form: Name / Category / Description before creating',
      'Create & Open launches a blank named SM in a new tab — then ★ to save',
      'Removed duplicate Standards button from toolbar — only top tab remains',
      'Tabs now select, not toggle: clicking ★ Standards always goes to Standards',
      'Clicking a project tab while on Standards returns you to the canvas',
    ],
  },
  {
    version: '1.13',
    date: '2026-04-20',
    time: '09:00',
    author: 'Dan Belliveau',
    changes: [
      'Standards Library: global template bank persisted in localStorage',
      '★ button on SM header saves the current SM (nodes, edges, devices) to the library',
      'Standards tab in tab bar — pinned, always visible, opens the library view',
      'Library view: searchable list with name, category, description',
      'Open any standard as a new project tab (fully functional, exportable to L5X)',
    ],
  },
  {
    version: '1.12',
    date: '2026-04-19',
    time: '21:00',
    author: 'Dan Belliveau',
    changes: [
      'L5X export: R05_Recovery routine generated from recovery sequence nodes',
      'R00_Main now includes JSR(R05_Recovery,0) between R03 and R20',
      'Recovery entry: State 127 (fault) auto-transitions to first recovery state',
      'Recovery transitions use same verify conditions as R02 (sensor/timer gating)',
      'Final recovery node transitions to State 2 (Auto Idle) on completion',
      'Empty recovery sequence: R05 emits NOP — manual FaultReset path preserved',
    ],
  },
  {
    version: '1.11',
    date: '2026-04-19',
    time: '18:00',
    author: 'Dan Belliveau',
    changes: [
      'Recovery sequences per SM: states 100-124 (+3 intervals), fault = 127',
      'Normal/Recovery toggle in canvas header — red button for recovery mode',
      'Recovery mode canvas is fully functional: add/edit/delete nodes & edges',
      'Recovery variant support: multiple named sequences per SM (recipe-ready)',
      'computeStateNumbers accepts startAt option (100 for recovery, 1 for normal)',
      'Store actions: addRecoverySeq, addRecoveryNode, addRecoveryEdge, and matching delete/update',
    ],
  },
  {
    version: '1.10',
    date: '2026-04-19',
    time: '14:00',
    author: 'Dan Belliveau',
    changes: [
      'Wait node redesign: device name (bold) + DI[2] / On / SignalName all on one row',
      'Live signal linking: Robot signal names update instantly when renamed in robot builder',
      'Correct DI/DO label for robot signals (robot perspective, not PLC tag prefix)',
      'Device name uses displayName (human-readable) not PLC tag name',
      'Cross-SM device lookup: searches all SMs for robot devices',
      'Wait mode popup defaults to Single exit (1); Decide defaults to Branch (2)',
      'Switching mode tabs resets exit count appropriately',
    ],
  },
  {
    version: '1.9',
    date: '2026-04-19',
    time: '10:00',
    author: 'Dan Belliveau',
    changes: [
      'Decision popup opens directly to the builder — no separate signal picker page',
      'Signal / Condition panel always visible in builder with "+ Pick Signal" CTA',
      'Done button disabled until a signal/condition is picked (prevents half-configured nodes)',
      'Multi-outcome decide nodes: dynamic handles for 3+ outcomes with color-coded labels',
      'Decide mode: single-exit option hidden (decide always branches 2+)',
      'Shortened exit labels to just On/Off/Pass/Fail/True/False — device name already on node',
      'Bold colored On/Off pill restricted to verify mode (decide is a fork, both paths equal)',
      'Fixed wait/decision exit-single edges: now Z-bend like regular state nodes (was L-bend)',
      'ConnectMenu tracks actual clicked handle ID instead of hardcoding exit-pass',
      'enforceNodeClearance runs on ALL edges (auto + manual) to push segments 25px off nodes',
    ],
  },
  {
    version: '1.8',
    date: '2026-04-18',
    time: '16:30',
    author: 'Dan Belliveau',
    changes: [
      'Multi-project tabs: open multiple projects simultaneously',
      'Dark navy tab bar above toolbar with project names',
      'Click tab to switch, X to close, + to open another project',
      '"+ Tab" button in Project Manager opens project in new tab',
      'Project state preserved per tab (SM selection, recipe, undo history)',
      'Network tab on IO Map: EtherNet/IP topology + backplane layout',
      'Auto-discovers servo, vision, robot, conveyor devices from state machines',
      'IP addressing follows SDC standard: subnet + decade offsets per device type',
    ],
  },
  {
    version: '1.7',
    date: '2026-04-17',
    time: '15:00',
    author: 'Dan Belliveau',
    changes: [
      'Network tab on IO Map: EtherNet/IP device topology + backplane layout',
      'Editable module names, catalog numbers, IP addresses, RPI rates',
      'Chassis visual: slot layout with DI/DO/AI/AO/Safety module types',
      'IP Address Summary view for quick reference',
      'Add manual EtherNet/IP modules and backplane modules',
    ],
  },
  {
    version: '1.6',
    date: '2026-04-17',
    time: '09:30',
    author: 'Dan Belliveau',
    changes: [
      'In-app Design System editor tab on Project Setup',
      'Visual reference for all colors, shapes, icons, typography, spacing',
      'Editable color swatches persist to project.designTheme',
      'Live SVG previews of node shapes and device icons',
      'SDC color palette applied to IO Map',
      'Consistent DeviceIcon SVG components throughout decision popup',
    ],
  },
  {
    version: '1.5',
    date: '2026-04-16',
    time: '14:30',
    author: 'Dan Belliveau',
    changes: [
      'IO Map tab on Project Setup: Device List + IO Map sub-tabs',
      'Device List groups by category with DI/DO/AI/AO counts',
      'Vision Systems split into own category in IO Map',
      'Part Tracking toggle in decision node popup (Wait/Decide/Verify)',
      'Auto-create PT fields from decision nodes on Done',
      'PT badge shown on decision nodes when enabled',
    ],
  },
  {
    version: '1.4',
    date: '2026-04-16',
    time: '10:15',
    author: 'Dan Belliveau',
    changes: [
      'Moved Release Notes button to sidebar below Rev number',
      'Enlarged Part Tracking and Signals section headers',
      'Cleaned up toolbar — removed version clutter from top bar',
    ],
  },
  {
    version: '1.3',
    date: '2026-04-16',
    time: '08:45',
    author: 'Dan Belliveau',
    changes: [
      'Refactored all edge routing into edgeRouting.js module',
      'Fixed edge shape preservation when dragging connected nodes',
      'Terminal run adjustment keeps drawn shape frozen, stretches only endpoints',
      'Removed duplicate routing code from RoutableEdge and Canvas',
      'Added version badge with changelog popup',
    ],
  },
  {
    version: '1.2',
    date: '2026-04-15',
    time: '16:00',
    author: 'Dan Belliveau',
    changes: [
      'Decision node modes: live exit labels, sensor/signal/vision branching',
      'Proximity handles on decision nodes',
      'Edge routing fixes for backward and sideways edges',
      'UI polish and label sync improvements',
    ],
  },
  {
    version: '1.1',
    date: '2026-04-14',
    time: '11:20',
    author: 'Dan Belliveau',
    changes: [
      'CompactLogix Motion (ERM) processor support',
      'L5X export fixes for program-scoped BOOL tags',
      'Part tracking panel and robot sequencing',
      'Analog probe flow support',
    ],
  },
  {
    version: '1.0',
    date: '2026-04-12',
    time: '09:00',
    author: 'Dan Belliveau',
    changes: [
      'Initial release: state machine editor with L5X export',
      'Node alignment tools, start conditions, index sync',
      'Supervisor L5X generation',
      'Controller-level L5X export',
    ],
  },
];
