/**
 * Application revision number + changelog.
 * Incremented on every push to GitHub.
 * Minor bumps (1.1 -> 1.2) on regular pushes.
 * Major bumps (1.x -> 2.0) on request for larger changes.
 */
export const APP_VERSION = '1.24.1';

/** Changelog — newest first. Keep entries short. */
export const CHANGELOG = [
  {
    version: '1.24.1',
    date: '2026-04-23',
    time: '08:55',
    author: 'Dan Belliveau',
    changes: [
      'Edit Subject modal for Servo Axis: "Subject Name" is now labelled "Axis Name" (matches how CEs talk about servos). Hint reflects the servo tag conventions (a01_{name}, p_{name}Home, …).',
      'Edit Subject modal for Servo Axis: "PLC Tag Stem" field hidden — servo tag generation is driven entirely by the axis name and fixed SDC conventions, so the stem just duplicates the axis name. Stem still auto-syncs in state under the hood so downstream tag generation is unchanged.',
      'Non-servo devices keep both fields (Subject Name + PLC Tag Stem) — those need the escape hatch when the ME name doesn\'t map cleanly to a PLC identifier.',
    ],
  },
  {
    version: '1.24',
    date: '2026-04-22',
    time: '17:15',
    author: 'Dan Belliveau',
    changes: [
      'Wait node subtitle now names the SPECIFIC tag that advances the step (e.g. "q_MagnetLoadRobotMagnetPickClear = ON") instead of the owning device ("Magnet_Load_Robot = ON") — you were waiting on the robot\'s output bit, not the robot itself.',
      'Subtitle prefers the exact PLC tag when available, falls back to the signal name with the source prefix stripped ("Magnet_Load_Robot MagnetPickClear [3]" → "MagnetPickClear [3]"). Honors Wait Off so OFF waits no longer mis-label as ON.',
      'Single-exit wait edges now render plain gray like any other sequential state-to-state edge — they were rendering green as if they were a pass branch. A wait with one exit isn\'t a decision; every state needs a condition to advance, this is no different.',
      'Existing project data: Canvas render-layer strip of stale colored-branch styling on `exit-single` edges — no data migration needed.',
      'New single-exit edges created by addDecisionSingleBranch + ClampServoIndex template + onConnect now persist as plain sequential edges (no `isDecisionExit`/`exitColor` flag, no hardcoded green stroke).',
      'Decision node icon now uses the actual device type (Robot / Stamper / ServoAxis / VisionSystem / …) instead of the generic DigitalSensor/AnalogSensor fallback. Robot signals were being masked because they flow through the sensor pick path — `liveDevice?.type` now wins over `isSensor`.',
    ],
  },
  {
    version: '1.23.1',
    date: '2026-04-22',
    time: '21:30',
    author: 'Dan Belliveau',
    changes: [
      'Fix: "Offline" pill stuck on even after a successful boot sync — writeCache fired the change notification before serverReachable flipped to true, so the UI read a stale flag. Flag is now set BEFORE the cache write.',
      'Remove aggressive fs.accessSync W_OK probe on the shared standards path — Windows reports SMB permissions inconsistently and the probe was rejecting writable paths. A successful mkdirSync is enough evidence; real read/write errors now surface cleanly as HTTP 5xx.',
      'New diagnostic endpoint: GET /api/standards/_debug returns the resolved standards dir + file path + entry count. Hit it from the browser when the Offline pill stays on to see which path the server chose.',
      'Standards API: console.info log on successful boot sync (# of standards pulled).',
    ],
  },
  {
    version: '1.23',
    date: '2026-04-22',
    time: '21:00',
    author: 'Dan Belliveau',
    changes: [
      'Standards Library is now TEAM-SHARED — backed by a single JSON file on the N:\\ drive',
      'Save a standard on one machine → every teammate sees it on their next Refresh (or next app launch)',
      'New /api/standards endpoints (GET/POST upsert/DELETE) with auto-backup of the last 5 versions',
      'Electron desktop app defaults standardsDir to N:\\AI Folder\\State Logic Diagrams\\standards with graceful fallback to local AppData if the share is unreachable',
      'localStorage is now only an offline cache — app stays usable without network, syncs when it comes back',
      'StandardsView: "● Shared" / "● Offline" pill shows sync status; new Refresh button pulls latest from server',
      'Import now pushes merged/replaced library to the shared server so everyone sees the imported entries',
      'Removed the public/standards-seed.json fetch-on-first-launch flow — superseded by real sync',
    ],
  },
  {
    version: '1.22',
    date: '2026-04-22',
    time: '16:30',
    author: 'Dan Belliveau',
    changes: [
      'Decision node: "Branch" badge renamed to "Decide" (only on actual decide-mode nodes, not wait nodes with 2 exits)',
      'Wait node branching rule: a single-condition wait can\'t branch — if the condition isn\'t met, the state just doesn\'t advance. "2 branches" button hidden when wait + ≤1 condition',
      'Decide-mode advance-when text now uses LIVE state numbers ("Magnet_PNP has reached State 4") instead of baked "→ Step 3" — never goes stale on renumber',
      'State-signal resolver falls back to matching by state name when the signal lacks a stored node-id (older signals)',
      'addDecisionSingleBranch cleans up excess edges when collapsing a multi-exit node to single-exit — orphaned empty child nodes removed',
      'Mode switcher: switching to wait collapses multi-exit to single when ≤1 condition; verify always collapses to single',
      'Standards library: ships with a seed file (public/standards-seed.json) that auto-imports on first run if localStorage is empty',
      'Standards library: Export / Import JSON buttons in the Standards header — back up or share your library as a file',
    ],
  },
  {
    version: '1.21',
    date: '2026-04-22',
    time: '15:20',
    author: 'Dan Belliveau',
    changes: [
      'Edge clearance: source/target nodes now push their own edge\'s stub-adjacent segments when dragged across them',
      'Dragging a source node DOWN pulls the bottom horizontal with it — no more snap-above-node',
      'Handle-based push direction: bottom-handle source pushes own seg down, side handles push outward, target pushes own seg up',
      'Owner-biased pushes no longer gated by corridor check — force to correct side whenever X ranges overlap',
    ],
  },
  {
    version: '1.20',
    date: '2026-04-22',
    time: '11:00',
    author: 'Dan Belliveau',
    changes: [
      'Standards auto-save — new standards are written to the library immediately on creation; every subsequent edit auto-saves (400ms debounce)',
      'Tab switches / unmounts flush any pending standards save — edits are never lost',
      'Standards-linked tabs show a green "★ Saved" pill in the SM header instead of the star button',
      'Copy button on each library card duplicates a standard to a new editable row with fresh UUIDs (nodes, edges, devices all independent)',
      'Inline rename — double-click a standard name in the library to edit; Enter/blur saves, Esc cancels',
      'Standards grouped by category with uppercase headers and per-category count pills; Uncategorized sorts last',
      'Click anywhere on a library card to open — the redundant Open button is gone',
      'Fix: SM name and description carry into library correctly on open + create',
    ],
  },
  {
    version: '1.19',
    date: '2026-04-22',
    time: '09:30',
    author: 'Dan Belliveau',
    changes: [
      'Design System → Canvas Spacing: editable "Vertical Node Gap" value (default 80px)',
      'Spacing is now a true gap — measured from bottom of one node to top of next, independent of node height',
      'Tall Home nodes no longer squish the visual gap to the next step',
      '+ Add State places new nodes at sourceBottom + gap using React-Flow measured heights',
      'New "Re-space" button in bottom canvas toolbar — applies the configured gap to existing nodes',
      'Re-space honors selection: ≥2 selected → only those nodes; nothing selected → all nodes',
      'Row-aware re-spacing — branch siblings at same Y stay paired after re-spacing',
      'Canvas Spacing input accepts free-typing (clear + retype), commits on valid values or Enter',
    ],
  },
  {
    version: '1.18',
    date: '2026-04-22',
    time: '07:15',
    author: 'Dan Belliveau',
    changes: [
      'Direction arrows now render on every segment longer than 60px — loops and U-bends show flow at each run',
      'Click Wait On / Verify On pill to open an On/Off switcher popup (matches StateNode action-pill UX)',
      'Wait node advance-when text is live — "Magnet_PNP in State 13" / "reached State 13" pulled fresh every render, no stale step references',
      'Signal-based wait pill toggles polarity (Wait On ⇄ Wait Off) instead of being locked on',
      'Inner action-row card tinted to match outer node color — softer contrast on verify/wait nodes',
      'Verify node drops the redundant advance-when row — branch labels already communicate On/Off',
    ],
  },
  {
    version: '1.17',
    date: '2026-04-21',
    time: '16:30',
    author: 'Dan Belliveau',
    changes: [
      'Direction arrows on all edges — subtle chevron mid-last-segment shows flow direction',
      'Unified wait/verify/decide nodes with StateNode ActionRow layout: [icon] [subject bold] [op badge] + advance-when text',
      'Op badge dynamically labels the node: Wait On / Wait Off / Verify On / Verify Off / Branch / Vision / Wait Range / Verify Range',
      'L5X export: SM output tag prefix q_ (was p_) — matches SDC standard for output parameters (non-latching OTE)',
    ],
  },
  {
    version: '1.16.5',
    date: '2026-04-21',
    time: '11:30',
    author: 'Abhi Kamuju',
    changes: [
      'Unsaved-changes guard on app close — matches Word/Excel behaviour',
      'Closing with unsaved work shows: Save / Don\'t Save / Cancel',
      'Save option writes to known file path instantly (no extra dialogs)',
      'Cancel returns to app; Don\'t Save closes immediately',
    ],
  },
  {
    version: '1.16.4',
    date: '2026-04-21',
    time: '11:15',
    author: 'Abhi Kamuju',
    changes: [
      'Load button uses native Electron dialog — remembers the opened file path',
      'Save now writes directly back to the opened file with no dialog and no "replace?" prompt',
      'Completely silent save: open file once, then Ctrl+S or Save button just overwrites instantly',
    ],
  },
  {
    version: '1.16.2',
    date: '2026-04-21',
    time: '10:45',
    author: 'Abhi Kamuju',
    changes: [
      'Fix: JSON save now writes correct file contents in desktop app (was saving 0 KB)',
      'Desktop app uses native Electron save dialog instead of browser File System Access API',
      'Browser (server-app1) continues to use showSaveFilePicker as before',
    ],
  },
  {
    version: '1.16.1',
    date: '2026-04-21',
    time: '10:30',
    author: 'Abhi Kamuju',
    changes: [
      'Fix: version display now correctly shows Rev 1.16.1 (1.16.0 built before version.js was synced)',
      'Save dialog no longer appends _backup to filename — overwrites existing file directly',
    ],
  },
  {
    version: '1.16',
    date: '2026-04-21',
    time: '09:00',
    author: 'Abhi Kamuju',
    changes: [
      'Desktop app: silent auto-update — downloads in background and restarts automatically',
      'No more update dialogs; app checks every 2 minutes and installs with a 5-second countdown',
      'Save dialog remembers last folder used (no more Downloads default)',
      'Toolbar buttons moved below canvas — no longer overlap diagram nodes',
    ],
  },
  {
    version: '1.15',
    date: '2026-04-20',
    changes: [
      'Replaced "S" signal badge with flag icon (⚑) on wait/decision nodes',
      'Avoids letter conflict with PLC "Set" / "State" conventions',
    ],
  },
  {
    version: '1.14',
    date: '2026-04-20',
    time: '11:00',
    author: 'Dan Belliveau',
    changes: [
      'SM title bar redesigned: bigger rounded pill with blue S01 badge',
      'Recovery mode turns the whole title bar red (bg, S01 badge, name text)',
      '+ New Standard button (rounded pill) in Standards Library header',
      'Inline naming form: Name / Category / Description before creating',
      'Create & Open launches a blank named SM in a new tab — then ★ to save',
      'Removed duplicate Standards button from toolbar — only top tab remains',
      'Tabs now select, not toggle: clicking ★ Standards always goes to Standards',
      'Clicking a project tab while on Standards returns you to the canvas',
    ],
  },
  {
    version: '1.13',
    date: '2026-04-20',
    time: '09:00',
    author: 'Dan Belliveau',
    changes: [
      'Standards Library: global template bank persisted in localStorage',
      '★ button on SM header saves the current SM (nodes, edges, devices) to the library',
      'Standards tab in tab bar — pinned, always visible, opens the library view',
      'Library view: searchable list with name, category, description',
      'Open any standard as a new project tab (fully functional, exportable to L5X)',
    ],
  },
  {
    version: '1.12',
    date: '2026-04-19',
    time: '21:00',
    author: 'Dan Belliveau',
    changes: [
      'L5X export: R05_Recovery routine generated from recovery sequence nodes',
      'R00_Main now includes JSR(R05_Recovery,0) between R03 and R20',
      'Recovery entry: State 127 (fault) auto-transitions to first recovery state',
      'Recovery transitions use same verify conditions as R02 (sensor/timer gating)',
      'Final recovery node transitions to State 2 (Auto Idle) on completion',
      'Empty recovery sequence: R05 emits NOP — manual FaultReset path preserved',
    ],
  },
  {
    version: '1.11',
    date: '2026-04-19',
    time: '18:00',
    author: 'Dan Belliveau',
    changes: [
      'Recovery sequences per SM: states 100-124 (+3 intervals), fault = 127',
      'Normal/Recovery toggle in canvas header — red button for recovery mode',
      'Recovery mode canvas is fully functional: add/edit/delete nodes & edges',
      'Recovery variant support: multiple named sequences per SM (recipe-ready)',
      'computeStateNumbers accepts startAt option (100 for recovery, 1 for normal)',
      'Store actions: addRecoverySeq, addRecoveryNode, addRecoveryEdge, and matching delete/update',
    ],
  },
  {
    version: '1.10',
    date: '2026-04-19',
    time: '14:00',
    author: 'Dan Belliveau',
    changes: [
      'Wait node redesign: device name (bold) + DI[2] / On / SignalName all on one row',
      'Live signal linking: Robot signal names update instantly when renamed in robot builder',
      'Correct DI/DO label for robot signals (robot perspective, not PLC tag prefix)',
      'Device name uses displayName (human-readable) not PLC tag name',
      'Cross-SM device lookup: searches all SMs for robot devices',
      'Wait mode popup defaults to Single exit (1); Decide defaults to Branch (2)',
      'Switching mode tabs resets exit count appropriately',
    ],
  },
  {
    version: '1.9',
    date: '2026-04-19',
    time: '10:00',
    author: 'Dan Belliveau',
    changes: [
      'Decision popup opens directly to the builder — no separate signal picker page',
      'Signal / Condition panel always visible in builder with "+ Pick Signal" CTA',
      'Done button disabled until a signal/condition is picked (prevents half-configured nodes)',
      'Multi-outcome decide nodes: dynamic handles for 3+ outcomes with color-coded labels',
      'Decide mode: single-exit option hidden (decide always branches 2+)',
      'Shortened exit labels to just On/Off/Pass/Fail/True/False — device name already on node',
      'Bold colored On/Off pill restricted to verify mode (decide is a fork, both paths equal)',
      'Fixed wait/decision exit-single edges: now Z-bend like regular state nodes (was L-bend)',
      'ConnectMenu tracks actual clicked handle ID instead of hardcoding exit-pass',
      'enforceNodeClearance runs on ALL edges (auto + manual) to push segments 25px off nodes',
    ],
  },
  {
    version: '1.8',
    date: '2026-04-18',
    time: '16:30',
    author: 'Dan Belliveau',
    changes: [
      'Multi-project tabs: open multiple projects simultaneously',
      'Dark navy tab bar above toolbar with project names',
      'Click tab to switch, X to close, + to open another project',
      '"+ Tab" button in Project Manager opens project in new tab',
      'Project state preserved per tab (SM selection, recipe, undo history)',
      'Network tab on IO Map: EtherNet/IP topology + backplane layout',
      'Auto-discovers servo, vision, robot, conveyor devices from state machines',
      'IP addressing follows SDC standard: subnet + decade offsets per device type',
    ],
  },
  {
    version: '1.7',
    date: '2026-04-17',
    time: '15:00',
    author: 'Dan Belliveau',
    changes: [
      'Network tab on IO Map: EtherNet/IP device topology + backplane layout',
      'Editable module names, catalog numbers, IP addresses, RPI rates',
      'Chassis visual: slot layout with DI/DO/AI/AO/Safety module types',
      'IP Address Summary view for quick reference',
      'Add manual EtherNet/IP modules and backplane modules',
    ],
  },
  {
    version: '1.6',
    date: '2026-04-17',
    time: '09:30',
    author: 'Dan Belliveau',
    changes: [
      'In-app Design System editor tab on Project Setup',
      'Visual reference for all colors, shapes, icons, typography, spacing',
      'Editable color swatches persist to project.designTheme',
      'Live SVG previews of node shapes and device icons',
      'SDC color palette applied to IO Map',
      'Consistent DeviceIcon SVG components throughout decision popup',
    ],
  },
  {
    version: '1.5',
    date: '2026-04-16',
    time: '14:30',
    author: 'Dan Belliveau',
    changes: [
      'IO Map tab on Project Setup: Device List + IO Map sub-tabs',
      'Device List groups by category with DI/DO/AI/AO counts',
      'Vision Systems split into own category in IO Map',
      'Part Tracking toggle in decision node popup (Wait/Decide/Verify)',
      'Auto-create PT fields from decision nodes on Done',
      'PT badge shown on decision nodes when enabled',
    ],
  },
  {
    version: '1.4',
    date: '2026-04-16',
    time: '10:15',
    author: 'Dan Belliveau',
    changes: [
      'Moved Release Notes button to sidebar below Rev number',
      'Enlarged Part Tracking and Signals section headers',
      'Cleaned up toolbar — removed version clutter from top bar',
    ],
  },
  {
    version: '1.3',
    date: '2026-04-16',
    time: '08:45',
    author: 'Dan Belliveau',
    changes: [
      'Refactored all edge routing into edgeRouting.js module',
      'Fixed edge shape preservation when dragging connected nodes',
      'Terminal run adjustment keeps drawn shape frozen, stretches only endpoints',
      'Removed duplicate routing code from RoutableEdge and Canvas',
      'Added version badge with changelog popup',
    ],
  },
  {
    version: '1.2',
    date: '2026-04-15',
    time: '16:00',
    author: 'Dan Belliveau',
    changes: [
      'Decision node modes: live exit labels, sensor/signal/vision branching',
      'Proximity handles on decision nodes',
      'Edge routing fixes for backward and sideways edges',
      'UI polish and label sync improvements',
    ],
  },
  {
    version: '1.1',
    date: '2026-04-14',
    time: '11:20',
    author: 'Dan Belliveau',
    changes: [
      'CompactLogix Motion (ERM) processor support',
      'L5X export fixes for program-scoped BOOL tags',
      'Part tracking panel and robot sequencing',
      'Analog probe flow support',
    ],
  },
  {
    version: '1.0',
    date: '2026-04-12',
    time: '09:00',
    author: 'Dan Belliveau',
    changes: [
      'Initial release: state machine editor with L5X export',
      'Node alignment tools, start conditions, index sync',
      'Supervisor L5X generation',
      'Controller-level L5X export',
    ],
  },
];
