/**
 * whatsNew.js — single source of truth for the in-app version badge.
 *
 * UPDATE THIS FILE WITH EVERY CHANGE BATCH — Dan reads it in the app.
 *
 * How to update:
 *   1. Bump UI_BUILD (v2.<minor>.<n>) and BUILT_AT.
 *   2. Add a new entry to the FRONT of SHIPPED with plain-English,
 *      Dan-facing lines (what he can see/do, not implementation detail).
 *   3. Prune IN_PROGRESS — move finished items into the new SHIPPED entry.
 */

export const UI_BUILD = 'v2.6.34';

export const BUILT_AT = '2026-08-30';

// Newest first. items are short, plain-English, user-visible changes.
export const SHIPPED = [
  {
    version: 'v2.6.34',
    date: '2026-08-30',
    items: [
      'DEADLOCK REPAIR — the Pick and Place\'s two outgoing handshake signals (part gripped, part clear) that an earlier rewrite dropped are restored in their canonical shape and re-paired; both machines\' signal graph is green. The engine now treats introducing a forever-wait as an objective failure — a turn that culls or orphans an outgoing Signal step gets bounced and must restore it (signals are legal steps in the data even though the flow doesn\'t draw them)',
      'THE SIGNAL CHECK NOW BLOCKS THE BUILD for can-hang-forever findings (a wait no one ever signals, a circular deadlock): the button becomes "Fix these first", with "build anyway — the code carries these as-is" as the explicit secondary. Advisory findings (dead signal, fault-window) stay carry-as-is',
      'BUILD STATION CODE — the Generate card is renamed and is only about code now (the diagram already lives on the sheet): same two lanes (Accept station — move to the next / build this station\'s code now), same optional scope note',
      'REVIEWER COVER NOTE — every build lands with a cover note next to the file, in the JARVIS Deliveries pattern: what the station is, what standards and exemplar were applied, what was verified (import simulation, sequence cross-check, internal review findings), declared deviations, red pen invited',
      'Flow edge conditions read "Wait — Part-Gripped" and never truncate — the band grows to the full text',
    ],
  },
  {
    version: 'v2.6.33',
    date: '2026-08-30',
    items: [
      'CODE GENERATION RUNS ON THE FULL ENGINE — the writer is now the same Claude Code engine as the chat, with read-only eyes on the real reference folders (standard templates, engineer-verified exemplars, concept lessons, shipped files) while it writes. Every objective gate is unchanged: plan schema, deterministic template merge, byte-level validation with full import simulation, cross-check against your approved sequence, one adversarial internal review',
      'STUDYING AHEAD DURING YOUR WALK — from the devices approval onward, every step you approve quietly runs the pre-write study on the sheet so far; anything the code will need surfaces as a numbered question right then, so Generate starts with zero questions left. No code is written until you hit Generate',
      'BUILT-STATION CORRECTIONS ON THE FULL ENGINE — chat on a linked sheet now runs the same engine as fresh drafts: your correction edits the built sheet directly (split machines or the station sequence/recovery), lands in the change log, and the old one-shot corrections path is deleted',
      'One engine, every door — the honest map of what runs on what is on the Jarvis page > App flow, along with the audited one-store growth loop',
    ],
  },
  {
    version: 'v2.6.32',
    date: '2026-08-30',
    items: [
      'FLOW LOOKS LIKE V1 NOW — sequence and recovery diagrams render with the real v1 canvas language: the actual state-node cards (step number, header, action rows), the purple decision pill, real edges with condition labels ("when Part-Gripped") and Yes/No branch labels, counterpart tags riding the edges. Read-only, auto-laid-out, fits the card. Same content rules as before: no wait/home/signal boxes — waits live on the edges, exactly like the v1 canvas',
      'DESCRIBE-A-STATION SPLIT NOW RUNS ON THE FULL ENGINE — the moment you finish explaining, the same Claude Code engine that handles chat proposes the machine split (with its own reviewer pass and identity lock: approved machine names survive corrections verbatim). One brain end to end; the old one-shot splitter is deleted',
    ],
  },
  {
    version: 'v2.6.31',
    date: '2026-08-30',
    items: [
      'THE SEQUENCE IS A DIAGRAM — sequence cards render as a simple vertical flow: typed step nodes, decision diamonds with Yes/No branch paths, interaction tags riding along. Recoveries draw the same way. Simple on purpose: no state numbers, no tag names — the approved flow IS the diagram, and Generate compiles numbering/tags/init from it',
      'RECOVERY = BRANCHES ON THE SHIPPED PATTERN — no more prose with inline "if"s: recoveries re-shaped onto our standard home pattern (retract vertical → branch on gripper: carrying finishes forward, empty returns), your two stations re-fit with content unchanged, marked red. Filed one question asking which shipped jobs have recovery flows worth learning — drop them in the JARVIS Inbox',
      'CLEAN LINES: pneumatic actions are the whole statement ("Retract Vertical Slide" — no "— to clear height"); servo moves carry their named position ("Servo Move X Axis — Place Position"); named things are Title Case everywhere. The engine and its reviewer enforce all of it',
      'The scheduler-style bar family: reload bar bottom-center (navy/yellow, one button); the updates card docks in the step-guide rail — nothing floats over your content while you scroll',
    ],
  },
  {
    version: 'v2.6.30',
    date: '2026-08-30',
    items: [
      'SEQUENCE LINES ARE LINKED TO REAL DEVICES — no more "Z"/"X" shorthand: every action line references the actual device (Vertical Slide, X Axis) by a live link, so renaming a device instantly re-renders every sequence and recovery line that touches it, marked red until ✓ got it. Your existing lines migrate on load (anything unresolvable becomes a question, never a guess); the engine and its reviewer now reject made-up device names outright',
      'THE THREE-TIER INTAKE — safe to hand to any engineer: station data changes apply as always; a stated RULE about how Jarvis should behave files as a standing law (yours activate immediately; anyone else\'s wait in a queue on the Jarvis page for your approval); asks that need APP changes are filed — verbatim, attributed, with Jarvis\'s reading — into an app-suggestions queue for your review, never faked with data edits. Both queues live on the Jarvis page > What Jarvis knows',
      'INPUTS FOLD — once your walk is underway the reference material + explanation band collapses to one line ("▸ INPUTS — 4 files · explanation · 2 layers"); your choice sticks per draft, and + Add a layer stays one click away from the folded line',
    ],
  },
  {
    version: 'v2.6.29',
    date: '2026-08-30',
    items: [
      'THE REAL HARNESS IS EMBEDDED — the chat now runs the same engine as the assistant you compare it to (the Claude Agent SDK), living in the server with ONLY the station tools: it reads the sheet, the knowledge, and the shipped code, and edits station data — no file system, no shell, no reach into the app (verified: it refuses honestly). One session per station draft, so the conversation genuinely remembers across turns. All regression fixtures pass through it; the old engine is deleted',
      'THE PAGE IS ALWAYS CURRENT — drafts now live on the server as the single source of truth and every open page subscribes: any change (a chat turn, a background fix, another engineer someday) appears on your screen within about a second, marked in RED until you ✓ got it. The 7-line recovery that sat invisible on a stale tab can\'t happen again',
      'THE LOOP YOU ASKED FOR — tell it → it does it → the changed items highlight red (sequence lines, recovery lines, devices) → you look → "✓ got it" clears them, or keep talking. A floating "● updates on the sheet — Show" pill appears when changes land anywhere you\'re not looking',
      'Your edits always win a collision: if a save crosses paths with an engine change, your name/description/sheet edits stand and the engine artifacts take the newest copy — nothing silently lost either way',
    ],
  },
  {
    version: 'v2.6.28',
    date: '2026-08-30',
    items: [
      'THE ENGINEER GUIDES THE WALK — every reply ends with what just closed, what\'s still open, and the concrete next move ("hit Approve on the recovery step — next is the Escapement\'s devices"); when an edit changed something on screen it says where to look. Saying just "agree" now closes the open question(s) on your step instantly — same as clicking Agree — and tells you what\'s next',
      'THE RELOAD BAR (from the SDC Scheduler): when a newer build ships or your tab goes stale, one bar appears bottom-center — "A newer version is available. [Reload now]" — reloading never loses a keystroke (drafts flush first). Nobody will ever tell you to hard-refresh in the chat again',
      'YOUR ESCAPEMENT RECOVERY LANDED — the dictation that got dropped (gripped+part → finish forward and hold ready for pick; no part or not gripped → gripper open, shuttle back to the bowl, finger down = home) is on the FAULT RECOVERY panel, starved-feed handling kept. New law: a message with several things in it lands ALL of them — answers, recovery, directives — or says plainly what it didn\'t get to',
      'AUDIENCE TOGGLE (ME | CE) on the chat header: ME (default) gets pure machine talk — no tags, no PLC-speak; CE gets full controls detail. Per browser. Plus honest turn progress: activity narration + elapsed clock (percent is gone), connection loss reconnects to the still-running turn, and the failed-turn line has a Retry button',
      'Speaking to who\'s there, guiding where you are — turns run on the top reasoning model (your call: correctness over cost); station AI budget raised to $25 so a real walk never strands with a disabled Send',
    ],
  },
  {
    version: 'v2.6.27',
    date: '2026-08-28',
    items: [
      'THE AGENT LOOP IS LIVE (Phase 1 — you approved it this morning): talking to Jarvis on a draft now runs a real working agent, not a one-shot prompt. He reads what he needs (the sheet exactly as you see it — tags included, the conversation, the standing rulings, the shipped-work precedents, the code library), makes each edit through a typed operation that returns the REAL diff, re-checks himself, and a reviewer walks the diffs against your message before anything renders. You watch it live — "reading the sheet… searching shipped work… editing… checking the work…"',
      'RECEIPTS CANNOT LIE ANYMORE — the receipt line is assembled from the diffs the edits actually returned, never from what the model says it did ("Done — 2 changes to Mid-Base Escapement\'s sequence (tags only — no lines touched)"). A request the turn could not finish says so honestly, and your text goes back in the box',
      'The one-shot correction paths for drafts are DELETED (one-door law) — tag feedback, device removals, question answers, everything you say on a draft goes through the loop. Caps: $1 / 90s / 25 steps per turn, honest wrap-up on cap. Regression fixtures (your finger-2 and tag transcripts) run through the real loop',
      'RECOVERY STEP restored to every machine\'s walk + STATION ACCEPT: at the end of a walk, accept the station (banks for the machine-level generate) or generate now for testing. The JARVIS Inbox folder is live at C:\\SDC-StateLogic\\JARVIS Inbox — drop anything; the librarian that reads it daily is next in line',
    ],
  },
  {
    version: 'v2.6.26',
    date: '2026-08-28',
    items: [
      'FIXED (the tag misapply) — TAG FEEDBACK NEVER DELETES LINES: "doesn\'t need to interact" now clears that line\'s counterpart tag and nothing else; deleting a step requires you explicitly asking to remove the step. The engine sees the tags as first-class data (structured steps), and the checker restores any line a revision drops without an explicit ask. Your Escapement draft self-heals on load: Home, the part-clear wait, and Repeat come back with an honest chat line; only the two tags you removed stay gone. Locked in as a paid regression test with your exact transcript (8/8 passing)',
      'ONLY REAL INTERACTIONS TAG — exactly two shapes count: waiting on another machine\'s signal, or signaling to it. A motion that merely mentions a machine ("Extend Shuttle to present the part to X") is a motion; Home and Repeat never tag',
      'SEQUENCES READ AS A TYPE-FIRST GRID — same breakdown as the diagram: action type column (Home | Wait | Extend | Retract | Close | Open | Signal | Move) then the object and detail, identical shape for every machine; the interaction tag column stays at right and tagged lines drop the counterpart from the text (the tag carries it). The shape comes FROM the engine — it now emits structured steps (action / target / detail / counterpart), which also hands codegen cleaner input',
    ],
  },
  {
    version: 'v2.6.25',
    date: '2026-08-28',
    items: [
      'FIXED (the Finger-2 bug) — DEVICE REMOVAL IS NOW ATOMIC: "get rid of finger 2" removed it from the proposal but the device CARD and its open question lived elsewhere and survived, while the receipt narrated the drop. Now one apply hits every artifact: the sheet device row goes, the device\'s open questions auto-close, its placement record clears — and the receipt only ever states what the before/after comparison actually shows. A narrated removal the sheet doesn\'t show prints an honest "part of that didn\'t apply" instead',
      'Your stuck draft self-heals on load: a device you explicitly told Jarvis to drop, that the proposal did drop but the sheet still showed, is cleaned up with one line in the chat saying exactly what happened',
      'FIXED — resuming a draft silently WIPED its chat history (the conversation the engine relies on). It survives resume now',
      'The checker now rejects half-removals: a device dropped from ownership but still named in a sequence line (or vice versa) bounces back to the thinker before you ever see it',
    ],
  },
  {
    version: 'v2.6.24',
    date: '2026-08-28',
    items: [
      'INTERACTIONS ARE SEQUENCE LINES — no separate interactions list to drift out of sync: signal lines live in each machine\'s sequence ("Wait for Escapement\'s part-ready signal"), tagged inline with the counterpart in TWO colors — blue for another machine in THIS station (program-to-program), purple for a different station (the station\'s external interface — an important distinction for the generated code, now written into the standing knowledge). The walk\'s Interactions step is a review lens DERIVED from those lines — grouped by counterpart, "complete and correct?" — and corrections there edit the sequences themselves, both sides. One word everywhere: "signal", never "handshake"',
      'FIXED — chat send failing with "chatHistory is not defined": three full-context fields were missing from the summarize entry point. The honest error with your text preserved worked exactly as designed and stays',
      'YOUR EXPLANATION IS EDITABLE — the "Your explanation" card on the cascade now has ✎ edit: rewrite or add to it any time, even mid-walk. Applying is a real thinking round through the same engine — it reconciles with everything you already approved (approved machines keep their names, untouched content carries verbatim) and the changes land as the live diff on the sequence cards with a receipt. Never a silent rebuild',
      'NOTHING YOU ASK FOR VANISHES — when the engine honors a request somewhere other than a visible sequence line (a blow-off pulse folded into the gripper-open parameters, say), Jarvis now tells you where it went in the chat instead of leaving you to think the message was eaten',
      'APP FLOW — new tab on the Jarvis page: the layers of how the create-station pipeline is actually constructed, stage by stage — what you do, the six sources Jarvis pulls from, the thinking, the check, what renders, and what your two moves fire. Plus the honest memory model (offline distillation carried on every call) and the ask-vs-decide rule. Kept current with the wiring',
      'Knowledge rides every call by construction — one shared context assembly (laws, precedents, archetype notes) is physically attached to the thinker, the checker, and the device-placement agent; the sheet\'s real device names now ride correction rounds so dictated words resolve against them',
    ],
  },
  {
    version: 'v2.6.23',
    date: '2026-08-28',
    items: [
      'DEVICE PLACEMENT IS AGENTIC, GATE-DRIVEN, AND CHECKED — no more guessing rules and no background calls: at the cascade gates (your explanation submitted; each Approve) a THINKER decides device↔machine ownership like an SDC controls engineer — from the shipped-work precedents, the station-archetype concepts, and standing knowledge — and a CHECKER trained on the same knowledge reviews it BEFORE it renders (ship/fix, one bounce: a bowl proposed onto the pick-and-place comes back on the escapement machine with the violation named). Jason\'s process, applied to the spec sheet',
      'EVIDENCE, NOT GUESSES — a precedent-backed placement is confident: no question, and the receipt cites the source ("in our shipped escapement stations the bowl is part of the state machine that includes the escapement — FlexFeeder, the escapement pattern"). Only a device class with genuinely NO SDC example asks — and the question says so: "I searched our shipped work and standards — no example of a PlasmaWelder on any station. Where does it belong?" Your answer files as dated doctrine — asked once, ever',
      'THE RENDER NEVER DEPENDS ON A MODEL CALL — devices keep their last-known machine while a placement pass runs or fails; a failure retries once quietly then says the real reason ONE time. The red "(200)" spam and the vanishing devices are dead (root causes: a stale server build answering HTML, and last-known homes being ignored)',
      'The thousand-bowl fact is written down (station archetypes: bowl + escapement + nest are part of the feeding state machine, never the pick-and-place) — the missing knowledge that caused the guess in the first place',
    ],
  },
  {
    version: 'v2.6.22',
    date: '2026-08-27',
    items: [
      'MOVE A DEVICE BY SAYING SO — "FeederBowl belongs to the Escapement" in the chat moves it instantly: it leaves this machine\'s step, appears on the other\'s, the receipt says so, and your word outranks every automatic signal',
      'Drafts mirror to the server on every save (sans pictures) so a live incident is diagnosable from real data',
    ],
  },
  {
    version: 'v2.6.21',
    date: '2026-08-27',
    items: [
      'THE STEP IS THE SECTION — the duplicate step card is gone: the active section\'s own header carries "Step N of M · what\'s needed · Approve" (Devices, Sequence, Interactions, Fault recovery in turn). One surface, one home',
      'NUMBERED QUESTIONS — Q1/Q2/… sit at the top of the active section with Jarvis\'s proposal and ✓ Agree; they never appear twice. Answer by number in the chat ("1 — yes; 2 — actually there\'s a track-full sensor"): pure agrees record free, corrections route to their question in one round',
      'PER-MACHINE WALK — one machine all the way through (devices → sequence → interactions → fault recovery), then the next; the sheet auto-filters to the machine being walked and the filter chips follow (and are square now, per the app law). Questions about another machine\'s devices wait for THAT machine\'s step',
      'APPROVE AUTO-ADVANCES — the next step\'s section opens and scrolls into view immediately; the side guide still jumps back (re-opening marks downstream for re-confirm). Value asks stay red rows in the cards, counted in the header ("2 to answer · 1 value needed")',
    ],
  },
  {
    version: 'v2.6.20',
    date: '2026-08-26',
    items: [
      'NOTHING IS DRAWN BEFORE YOU AGREE — step 1 is now a DECOMPOSE-ONLY call (new /api/jarvis/decompose, cheap/fast tier, ~30s): your explanation goes in, ONLY the state-machine proposal comes back — names, one-liners, owned devices, per-machine sequences, and the asynchrony reasoning against your expectation. No diagram build, no compile. The drawn sequence and the code are THE LAST TWO steps, after every approval',
      'THE LEGACY BUILD-FIRST PATH IS DELETED — not disabled: the auto build+compile kick, the "Build — get the proposal" flow, and "Build without summary" are gone; retry, resume, and fresh submits ALL go decompose-only. One flow, one door (recorded as standing law in Jarvis\'s knowledge)',
      'NO MORE FROZEN BARS — the proposal call shows real elapsed time ("Proposing the state machines… 12s · typically ~30s"), warns past 60s, and hard-stops at 2 minutes with the reason and one Retry. Never a stuck 0%',
      'ARGUE WITH THE PROPOSAL IN THE CHAT — on a fresh draft, a chat message while step 1 is up re-proposes with your correction folded in ("his correction wins"); the reply lands in the thread with the new machine list',
      'APPROVING THE DRAFT SPLIT DRIVES THE WHOLE CASCADE — the per-machine devices → sequence steps derive from the proposal itself; the SM toggle shows the approved machines; and at Generate the approved split rides into the station (smSplit + approval + your cascade ✓s), so nothing you agreed is re-asked after the build',
    ],
  },
  {
    version: 'v2.6.19',
    date: '2026-08-26',
    items: [
      'EXPLANATION → SEND → GO — "Done explaining" now auto-kicks the state-machine proposal: the step-1 card shows the build progress, then "Jarvis is proposing the state machines…" with a live ring, then the proposal with Approve. The manual "Build — get the proposal" button is gone, and Approve NEVER shows before a proposal exists; a failed run shows the reason with one Retry button',
      'STEP 1 IS ONE CARD — the state-machines proposal, your "you expected: …" pills, the reasoning, rename, and Approve all live inside the cascade\'s step-1 card; the separate STATE MACHINES section above the sheet is gone in the guided flow',
      '"LEVEL OF CODE GENERATION" LEFT THE SHEET — the scope is now asked at the moment of generation: when every step is agreed, the Generate card offers "Full station — standard" / "Just the sequence & recovery — quick check" plus an optional one-line specifics box, right above the build button. The default stays the standard full station',
      'The chat\'s "applies to State machines by default" hint appears only once a proposal actually exists',
    ],
  },
  {
    version: 'v2.6.18',
    date: '2026-08-26',
    items: [
      'STRICT PROGRESSIVE DISCLOSURE — the sheet is now the conversation, top to bottom: your inputs (pictures + your explanation, permanently visible, read-only once submitted) → the ONE chat → the state-machine proposal → each machine\'s devices → sequence → recovery in turn → interactions → generate. Steps you haven\'t reached are HIDDEN entirely — nothing you said is lost (Jarvis keeps the full extraction; only the reveal is gated)',
      'THE STEP-BY-STEP GUIDE — a sticky side panel says how this is going to go and, per step, what information Jarvis needs to continue; ✓ / ● / ⟳ marks track progress and Generate closes the plan',
      'ONE CHAT, LIKE A PERSON — a single collapsible chat right below your inputs is THE conversation channel: the per-step response boxes are gone; a message while a step is active applies to that step by default (naming another section still routes there); "hide history" tucks the thread away',
      'QUESTIONS SURFACE WITH THEIR STEP — each step\'s card carries its own asks ("To agree on this, Jarvis needs: …") with proposed answers and one-click ✓ Agree; servo-value and geometry asks appear on that machine\'s devices step and jump to their table. No "Blocking code generation" strip before generation is the stage',
      'FRESH DRAFTS RUN THE CASCADE TOO — after "Done explaining" you see only your inputs, the chat, and the state-machines step (Build fetches Jarvis\'s proposal); devices and sequence reveal step by step after it',
      'A DRAFT WHOSE STATION WAS DELETED HEALS ITSELF — it returns to the unfinished-drafts list with your words and pictures intact; Build recreates the station',
      'Explanation hints match the cascade: cover how the station breaks down · the devices · the sequence · fault recovery · the challenges',
    ],
  },
  {
    version: 'v2.6.17',
    date: '2026-08-26',
    items: [
      'V2 IS THE APP NOW — opening http://localhost:3131 lands on the v2 shell (no more /v2.html to remember, though that link still works), and the production/desktop build ships v2 as the default for the first time',
      'V1 IS FROZEN AND ONE CLICK AWAY — the classic app lives at /classic.html, looking and working exactly as it always did; it ships in every build but nothing in it changes anymore',
      'Saving with Ctrl+S is untouched but its code moved to a safe home (lib/projectApi.js) so future exporter cleanup can never break saving',
      'Dead code removed: five superseded files (old Create Station modal, two legacy signal modals, an orphaned IO view, the removed v2 right panel) — about 1,050 lines gone, zero behavior change',
      'docs/V2_CAPABILITY_GAPS.md lists every v1 feature that still needs a v2 home (Standards browser first) with a proposed Jarvis-mediated approach for each — for Dan to prioritize',
    ],
  },
  {
    version: 'v2.6.16',
    date: '2026-08-26',
    items: [
      'THE SPEC SHEET IS NOW A PROPOSE → APPROVE CASCADE — a progress rail at the top of the Station band shows where you are (SM breakup ✓ → S01 devices ✓ → S01 sequence ● → … → Interactions). ONE proposal is active at a time with ONE response place: an Approve button and one talk/type box; approving locks the step ✓ into the outputs below (read-only, stamped, in the change log) and the cascade moves to the next thing',
      'THE ORDER IS YOURS — describe the station (unchanged), the FIRST proposal back is the state-machine breakup (approve it at the top or tell Jarvis how you\'d split it); once approved, each machine walks devices → sequence → recovery, then interactions/handshakes, then the sheet closes with "Looks good — build the code"',
      'EDITING A LOCKED STEP RE-OPENS IT — a device rename/add/remove, an interactions change, or a correction that actually changed a section re-opens that step, and every approved step downstream queues for a one-click ⟳ re-confirm. Pure value fills (positions, timers) stay instant and never re-open anything',
      'FLIP BETWEEN STATE MACHINES ON THE SHEET — "Showing: All | S01_… | S02_…" chips above the outputs show the SELECTED machine\'s devices, sequence and recovery (All = overview). Picking a machine on the sheet also selects it on the banner and the Diagram page; clicking a banner chip flips the sheet the same way',
      'Approvals persist per station (machineSpec.cascadeState — the SM breakup keeps its existing smSplitApproval artifact) and your earlier section-review ✓s carry over as already-approved steps',
      'EVERYTHING YOU SAID IS EXTRACTED UP FRONT — later cascade steps show as grayed previews ("up next") instead of hiding, so nothing you explained is forgotten while the current step is worked. You review, approve, adjust — never manually enter',
      'NAMING IS PART OF EACH STEP — state-machine names are worked during the SM-breakup step (inline rename there), device names during that machine\'s devices step: click a proposed name chip on the proposal card to adjust it; the rename cascades to sequence, diagram and tags',
      'BOM AS A REFERENCE INPUT — drop a bill of materials (xlsx/csv) into Reference material: it wears a BOM tag and seeds the device & I/O proposals at the next Build (full spreadsheet parsing lands with the ingest pipeline)',
      '"HOW JARVIS WORKS" IS NOW THE THINKING CONTRACT — the tab is rebuilt around Jason Perry\'s 14-step process, verbatim: one card per step with how Jarvis executes it and what information it needs from you (the two honest gaps — project release and URS intake — are flagged amber). The app-flow walkthrough moved into a small collapsible footnote',
    ],
  },
  {
    version: 'v2.6.15',
    date: '2026-08-25',
    items: [
      'ONE TRUTH ON THE STATE-MACHINES PANEL — it shows exactly one versioned decomposition at a time ("Proposal v2 — 4 state machines — awaiting approval"): cards, count and reasoning all from the SAME compile; a newer proposal supersedes the display of an older approval (which moves to the change log, noted as superseded). A proposal whose own reasoning disagrees with its machine list renders as an ERROR state and auto re-proposes — the contradiction never renders. The panel now lives at the TOP of the sheet with the inputs',
      'A COUNTER THAT AGREES NOW ACTUALLY CHANGES SOMETHING — "Send to Jarvis" on the decomposition routes through the classifier: a boundary change updates the sheet AND opens Re-compile pre-filled (explicit start), so the round ends in a NEW displayed proposal — never agreeing prose over an unchanged split. The compile route itself now rejects and retries once any output whose reasoning and machine list disagree. Verified live with the exact 4-SM counter on Magnet Dial',
      'OUTPUTS ARE READ-ONLY PROJECTIONS — sequence and fault-recovery lines no longer hand-edit, device add/remove is gone from the Station band: structural changes flow input → build → review → request change → rebuild. Instant inline edits remain ONLY for pure values and names (timers, positions, homes, direction, renames)',
      'BUILD ROWS SHOW THEIR FINAL VERDICT — v7 reads "✓ internal review: ship · 8 rounds", never a stale mid-loop "8 findings"; mid-loop findings in the expanded panel are labeled as history. The grid separates DELIVERED versions (v4/v5, v6, v7) from "+ N working builds" (collapsed intermediates), and the newest delivered row wears "latest — in JARVIS Deliveries"',
      'CLICK A BUILD, GET ITS DOSSIER — the expanded row shows the full round-by-round review timeline ("Round N · full/delta · verdict · note … 8 rounds → ship · shipped as …"), key assumptions, standards used, rulings & lessons applied ("X permissive per Jason 8/25"), structural changes flagged with approval state, and the questions the build asked',
      '"HOW A BUILD IS CHECKED" on How Jarvis Works — mechanical gates (free, instant) → THE CHECK (would a senior SDC controls engineer sign this?) → the three verdicts → the capped loop → the delivery gate. One screen, five cards',
    ],
  },
  {
    version: 'v2.6.14',
    date: '2026-08-25',
    items: [
      'REVIEW & EDIT MODE — after a Build, every sheet section (Interactions, Devices, Sequence, Fault recovery, IO, State machines) gets Edit and ✓ in its header: Edit opens one talk/type box ("what should change and why"), Jarvis answers with a PROPOSED old→new diff — Approve applies it (receipt + amber flash + quiet ✓ on the section), Reject keeps your words in the box for a retry. A progress line keeps score ("3 of 6 sections reviewed"); all reviewed → one clear "Looks good — build the code"',
      'CHANGE LOG — your version control view at the bottom of the sheet: one line per applied change (when · what · class chip · cost), newest first, collapsible. Section-edit approvals, corrections, renames, value saves and decomposition approvals all land there',
      'COMPILE FINDINGS STOP VANISHING — "self-check flagged N issues" now persists: closing the compile window lands you on the spec sheet with the findings pinned at the top (each links to its section) and the next step written out. "View compiled sequence" still available',
      'YOUR TEXT CAN NO LONGER BE EATEN — the state-machine counter box (and every send) keeps your words until a receipt confirms the round landed; a failure leaves them right there with the error line',
      'APPROVING THE DECOMPOSITION REORGANIZES THE SHEET IMMEDIATELY — approval materializes exactly what you see (never a stale older split), per-SM sequence columns appear with EACH machine\'s own fault-recovery column, and the change log records "Decomposition vN approved — N state machines"',
      'BLOCKERS COME IN EXACTLY THREE SHAPES — a value ask renders its real field (a timer ask creates the field ON its device — "vacuum off release timer" saves straight onto the Vacuum Cup); a question comes with Jarvis\'s proposed answer prefilled; everything else is a quiet note with ✓ agree that never counts in the red number. Robot-handshake asks render as the signal rows they are',
      'DIAL DIRECTION — rotary cards get a CW/CCW select and the motion-path dial arrow honors it (no more backwards dials)',
      'RENAMES CASCADE — click a device name (✎), change the wording, and the sequence lines, diagram labels, split ownership and generated tag names all follow; the change log records it. Jarvis still proposes standard names at extraction — your rename wins after',
      'SIGNAL CARDS CLEANED UP — the "from …" chip sits on its own row (never on top of a long name), names ellipsize with the full name in the tooltip, and card text is one short sentence (rung text lives in the tooltip, not the card)',
    ],
  },
  {
    version: 'v2.6.13',
    date: '2026-08-25',
    items: [
      'THE STATE MACHINES ARE NOW AN APPROVAL — after a compile, Jarvis\'s proposed decomposition shows as cards (name, one-liner, owned devices) with an Approve button. Your expectation shows beside it as PILLS distilled from your words (the raw dictation collapses under "▸ what you said" — never the paragraph), with a "you expected N — Jarvis proposes M" note and his reasoning when you differ. Approving locks it in: the sheet groups by it, diagrams and code follow it; renaming a machine (click its name) re-opens approval; move/merge/split by telling Jarvis in Corrections',
      'YOUR EXPECTATION ALWAYS DOES SOMETHING VISIBLE — type it before a compile and the sheet says "Jarvis proposes the state machines at the next Build / compile — your expectation rides along" (the silent no-op is fixed)',
      'DEVICES SORT LIKE THE CLASSIC APP — the "Other devices" dump is gone: SERVO AXES | PNEUMATICS | SENSORS (real inputs like Stack Present) | SIGNALS (inter-SM handshakes and flags, each showing "from S01_MagnetLoad" → destination + meaning) | COUNTERS & VALUES (retry and fixture counters). Handshakes with no card of their own list inside SIGNALS — the separate handshake strip is gone (one concept, one home)',
      'GROUPING FOLLOWS YOUR APPROVAL — device cards group under SM sub-headers and the per-SM sequence columns appear only once you approve the decomposition; before that the sheet stays flat and the proposal waits in its section',
    ],
  },
  {
    version: 'v2.6.12',
    date: '2026-08-25',
    items: [
      'YOU PROPOSE THE STATE MACHINES — a new optional talk/type line near Level of code generation: "State machines you\'re expecting" ("dial indexer SM, magnet shuttle SM, magnet pick SM, maybe robot?"). Jarvis weighs it seriously at compile: he agrees or counters with his asynchrony-test reasoning (a review flag names any difference) — never ignores it, never blindly obeys. The planned STATE MACHINES list shows his answer against your expectation',
      'THE SHEET ORGANIZES BY STATE MACHINE — once the machines are known (an applied split or a multi-SM compile), device cards group under SM sub-headers (plus an Unassigned bucket), the Sequence card shows one numbered sequence per SM (fault recovery per-SM when the data has it, shared otherwise), and a small Handshakes strip lists every signal between the machines. Single-SM stations look exactly as before',
      'THE CORRECTIONS CHAT SCROLLS — the thread caps at about 5-6 turns tall with internal scroll pinned to the newest turn, plus an "expand all / collapse" control. The one sanctioned scroll exception — everything else still grows',
      'JARVIS STOPS EXPLAINING YOUR OWN WORDS BACK — chat replies are terse by law: "Okay, got it." plus only his genuine questions; no step-by-step echoes of what you just said unless you ask "what did you understand". Verified live',
      'EVERY SHEET FIELD SHOWS IT SAVED — a quiet "⟳ saving… / ✓ saved" tick on the expected-state-machines line, the generation specifics, the reference line, and the Interactions header, driven by the real autosave',
      'REBUILD RE-THINKS — updating understanding-affecting fields (expected state machines, generation level, interactions) raises the "Sheet updated — Rebuild has Jarvis re-think with the new info" chip, and Rebuild carries all of it into the compile',
    ],
  },
  {
    version: 'v2.6.11',
    date: '2026-08-25',
    items: [
      'BRANCHES LEAVE AT THE CONNECTION POINTS — PERIOD. A loop or branch from a right-side exit can never again draw back through its own node: the loop rail is locked to the side the handle faces, and generated diagrams place every alternate/retry chain in its own column a full lane RIGHT (sub-branches half a lane further), so side exits are always a clean L-bend into the top of the next node',
      'THE MAGNET DIAL DIAGRAM IS REPAIRED IN PLACE — same states, same logic, new geometry: main spine in one column, Empty Fixture + fault right, strip-retry and pick-retry chains right with their exhausted paths a half-lane out, retry loops re-entering the spine BETWEEN nodes, restart loops railing around the outside. Verified zero edges through nodes, zero label overlaps, zero rail pile-ups (a pre-fix backup is in projects/_backups)',
      'EDGE LABELS NEVER HIDE BEHIND NODES — a label pill whose spot is covered by a node slides along its edge until it sits in open canvas',
      'LOOP RAILS STAGGER INSTEAD OF STACKING — several loop-backs sharing a side each get their own rail offset, and multiple returns into one node land at staggered heights with extra clearance above the node, so every return reads separately',
      'GENERATED LAYOUTS USE REAL HEIGHTS TWICE — Jarvis lays out with estimates, then the canvas re-runs the SAME column-aware layout once true node heights are measured (the old single-column respace is no longer used for this), so branch columns stay columns',
    ],
  },
  {
    version: 'v2.6.10',
    date: '2026-08-25',
    items: [
      'ANSWER BLOCKING QUESTIONS RIGHT WHERE THEY SIT — every question in the red "Blocking code generation" strip now has its own answer box PREFILLED with Jarvis\'s proposed solution and an Answer button: accepting is one click, typing over it overrides. Answers ride the same path as the Corrections chat — they land in the sheet, the blocker clears, and the receipt shows what changed',
      'ROTARY DIALS SPEAK FIXTURES AND DEGREES — a dial/index servo axis card now leads with "Fixtures (nests)" (red until you set it) and DERIVES the index increment as 360°/N (type over it for non-uniform dials). No more "IndexIncrement — mm": every position and speed on a rotary card reads ° and °/s, on the sheet and in the servo values table, and the fixture count persists onto the built station\'s Index row',
      'THE MOTION PANEL KNOWS A DIAL WHEN IT SEES ONE — a rotary axis draws as a simple dial glyph (circle, N fixture ticks, index arrow with the increment in °) instead of the wrong "a PNP path needs two" message; a dial with no fixture count asks for it plainly',
      'STATE MACHINES PLANNED — when a compile decomposes the station into multiple coordinated machines (dial index, feed shuttle, pick head), the sheet shows a compact "STATE MACHINES (N)" list near the plan: one line each. Older compiles without it show nothing',
    ],
  },
  {
    version: 'v2.6.9',
    date: '2026-08-24',
    items: [
      'A NEW PROJECT OPENS CLEAN — creating or switching projects clears every trace of the previous project\'s station context (the "Magnet Dial v3 opened showing ServoPNP\'s spec sheet" hijack is fixed). A new project lands on its own Project Home: zero stations, the + Add Station card, no leftover sheet or banner',
      'DRAFTS CAN\'T CROSS PROJECTS — a spec sheet or draft that was open when you switched projects can no longer save itself into the new project\'s drafts; every draft stays with the project it was written in',
      'YOUR DESCRIPTION SURVIVES RELOADS — if the app reloads or recovers mid-explanation, the create page silently picks up exactly where you were (within 10 minutes): no blank form, no banner, nothing to click. + New Station still always opens blank',
    ],
  },
  {
    version: 'v2.6.8',
    date: '2026-08-24',
    items: [
      'TELL JARVIS TO DEVIATE FROM STANDARD — say "single speed the whole time" or "no blending" in the Corrections chat: Jarvis pushes back ONCE like a CE (states the standard, asks you to confirm), and on your confirm he builds it your way, records it as an approved deviation on the station, and nobody downstream (compile, reviewer) ever flags or "corrects" it again. Reverting to standard applies immediately',
      'THE DIAGRAM READS LIKE A TABLE — Z point labels are collimated on rails (pick side left, place side right: Retract, Blend end, speed transition, Pick/Place) with dotted leaders to each height; nothing ever clips',
      'EQUAL BLENDS DRAW SQUARE — a 25/25 corner is a true symmetric quarter-round (both legs share one visual scale); unequal values read asymmetric in the right direction',
      'BLEND LIMITS ARE THE REAL PHYSICS — a blend may reach up to (speed transition − Retract) on the vertical leg (equal is allowed and ideal) and up to the full Pick↔Place travel on the horizontal; your 25 mm blends pass clean. The old half-gap rule is gone — bigger blends are faster, not warnings',
      'AXIS CARDS GROUP BY KIND — Positions, then Speed transitions, then Blends, with quiet micro-headers; the X card stays a plain two-row card',
    ],
  },
  {
    version: 'v2.6.7',
    date: '2026-08-24',
    items: [
      'THE MOTION PATH DIAGRAM IS HERE — the station sheet now DRAWS your pick-and-place path (your notebook sketch, machine-drawn): ONE square inverted-U from the live servo values — down at Pick, up to the single Retract height, across, down at Place — with every named point as a dot and its mm value, fast segments blue / slow segments amber, gripper close/open marked. Blending renders exactly as you sketched it: the square\'s theoretical corners stay visible (light dashed) and the actual path rounds them symmetrically, blend start/end dots on both legs. It stays a sane size and re-draws the moment you change a value; clicking any point label jumps to its row',
      'THE 2 mm BLEND PLACEHOLDERS ARE GONE — they were never your numbers. Both corner blends are now empty and red ("you set this") on the sheet, in the servo table, and on the diagram; they count as blockers until YOU type the values from the application. Jarvis no longer proposes corner-blend values — corner clearances are yours',
      'SHEET SERVO VALUES NOW WRITE THROUGH to the station instantly — the sheet rows, the diagram, and the built station are one live-linked set of values (clearing a cell clears it everywhere; abandoned placeholders can\'t resurrect)',
      'GEOMETRIC NONSENSE CAN\'T HIDE ANYMORE — arithmetic sanity checks run on every axis everywhere (sheet cards, servo table, the path diagram, the blocking strip): a transition beyond its target ("PlaceTransition 450 is beyond Place 300"), a blend bigger than half the smallest gap, anything outside the travel — the offending row flags RED with a plain sentence and counts as a blocker until fixed',
      'BLOCKING QUESTIONS NEVER TRUNCATE — every held item shows its FULL text (wraps, grows, no ellipsis, no "+N more"), and Jarvis\'s proposed answer is PREFILLED in the answer box instead of an empty demand. A held item that isn\'t actually a question renders as a quiet note, not a red ask',
      'THE DOUBLE GRIPPER SELF-HEALS — a sheet already carrying "Gripper" AND "Part_Gripper" collapses to ONE card the next time it opens (values, purpose, and delays all kept). The earlier fix only prevented new twins; this one merges twins that already exist',
      'X IS PICK AND PLACE, NOTHING ELSE — the invented X transitions (including the impossible PlaceTransition 450) are deleted from the sheet and the station; X\'s home defaults to Pick (it rests where init leaves it) and a new guard stops compile echoes from ever re-adding rows your table doesn\'t declare',
      'SPEED WINDOWS ARE GONE — the confusing "advanced" section is deleted everywhere: the blend start/end IS the window. Z\'s two fast/slow points now read "Pick speed transition" / "Place speed transition"; the code confirms arrival at them strictly (move complete + in position). The only windows in the system are your two corner blends',
      'EVERY DIAGRAM POINT SHOWS ITS FULL NAME AND VALUE — labels near the edges tuck inward instead of clipping ("PlaceTrans…" is fixed)',
      'THE PNP MOTION MODEL IS WRITTEN DOWN ONCE — jarvis-knowledge/concepts/motion-model-pnp.md is now THE authority (X: pick/place only, fast always; Z: the 7 canonical rows; blends at corners, never "after complete" chains; never invent points). Compile-side wiring rides in docs/TODO-pipeline-patches-2026-08-24.md until the build queue is idle',
    ],
  },
  {
    version: 'v2.6.6',
    date: '2026-08-24',
    items: [
      'CORRECTIONS IS NOW A CHAT WITH JARVIS — the same layer that generates the code. Type or talk in the Corrections box and Send: Jarvis applies the change, asks one clarifying question with his proposed answer, or just answers you. The thread persists on the sheet (recent turns visible, older ones expandable)',
      'THE RECEIPT CAN NO LONGER LIE — "what changed" is now COMPUTED by diffing the sheet before vs after, never taken from Jarvis\'s claims. A claim that didn\'t actually land shows as "⚠ could not apply — tell me again"; a change Jarvis made but didn\'t mention is flagged too. What you read is what the sheet actually did',
      'CORRECTIONS ARE AGENTIC — Jarvis receives the COMPLETE current sheet and returns the corrected sheet; the old client-side keep-rules no longer fight him. Saying "remove the duplicate gripper" now actually removes it — an explicit removal always wins and nothing resurrects it',
      'THE DOUBLE GRIPPER IS FIXED — ServoPNP shows ONE gripper (Part_Gripper, your 250 ms delays) on the sheet and in the station. Root cause: the station merge only matched device names exactly, so "Gripper" and "Part_Gripper" became twins; the merge now recognizes name variants of the same device and never adds a same-type twin next to an existing card',
      'SERVO CARDS READ LIKE YOUR LIST — Vertical Axis shows exactly: Retract, PickTransition, Pick, PickRetractBlend Start/End, PlaceTransition, Place, PlaceRetractBlend Start/End. Speed-change windows and legacy wideband rows are out of the card (they live under a tiny "advanced" expander); the explainer lines are gone (hover any row for its meaning); labels never wrap',
    ],
  },
  {
    version: 'v2.6.5',
    date: '2026-08-24',
    items: [
      'APPLY CHANGES NOW SHOWS A RECEIPT — after every Apply, a green "What changed" card lists one short line per change Jarvis made, and the touched rows/cards flash amber for 2 seconds. An apply that changed nothing says so. The card dismisses with × and is replaced by your next Apply — nothing is ever silent',
      'SHEET vs REBUILD is explicit: Corrections say "updates this sheet"; a quiet amber chip in the header ("Sheet updated since last build — Rebuild when ready") appears whenever the sheet is ahead of the diagram & code and clears on rebuild; the bottom button now reads "Rebuild station — apply sheet to diagram & code". Iterate on the sheet as long as you like — Rebuild once, deliberately, when everything is right. Apply never rebuilds anything by itself',
      'Rebuild progress speaks in full phrases ("Rebuilding the sequence from your sheet…") instead of truncated fragments',
      'DEVICE CARDS ARE TIGHTER — the description text is off the card header; hover the device name to read what it is for (still stored, still feeds Jarvis). Device names now always capitalize each word (XAxis, ZAxis, PartPresent) on extraction and on your own edits — existing devices are never renamed silently',
      'STANDARD PNP ASSUMPTION LEARNED: the pick nest has a part-present sensor and the cycle starts by waiting on it. The live ServoPNP station got its PartPresent sensor (i_PartPresent + debounce now in the devices and IO lists), and a station sheet now picks up devices added to the built station automatically',
      'STALE MODEL QUESTIONS CAN\'T LINGER — the "Needed from the mechanical model" banner now checks its questions against your CURRENT tables every time the sheet opens: a placeholder-values question auto-closes as stale the moment the tables hold real numbers (the old ServoPNP one is gone)',
      'BLEND ZONES ARE NAMED BY CORNER, per your sketch — the single RetractWideBand is now TWO independent values: "Pick retract blend start/end" and "Place retract blend start/end" (PickRetractBlend / PlaceRetractBlend on the axis), each its own mm number since the two corners can differ. Your agreed value seeded both — nothing reopened. One quiet line under the rows explains what a blend zone is',
      '"WIDEBAND" SPEAKS ENGLISH — transition rows read "PickTransition — speed-change window" (the fast/slow switch point — a different thing from a blend, kept visibly distinct). The built station keeps the PLC-safe tag names; the compile is told which corner uses which value',
    ],
  },
  {
    version: 'v2.6.4',
    date: '2026-08-24',
    items: [
      'EVERY DEVICE DECLARES ITS HOME on its card — servo axes get a "Home position" select (its own named positions; defaults smartly: a row named Home wins, vertical axes default to Retract) and pneumatics get a "Home state" select (cylinder Retracted / gripper Disengaged by SDC default). The declared home rides into the built station and into the compile, so Home Conditions, init, and recovery use YOUR home — never a guess',
      'Home also lives in the station Servo values table (Home position select per axis), edits write through to the station immediately, and your choice survives re-summarize / Apply changes like every other value',
      'The INTERACTIONS section now sits at the same readable width as Level of code generation and Corrections — the input boxes line up',
    ],
  },
  {
    version: 'v2.6.3',
    date: '2026-08-24',
    items: [
      'NO MORE SURPRISE "CREATE STATION" SCREEN — the bug that kept throwing you onto a blank new-station page (empty name, Station Number 2) under the ServoPNP banner is fixed: an open station sheet now always rebuilds itself from the station, never falls back to a blank create form. The create flow only ever opens when YOU click + Add Station or a draft',
      'WHILE CREATING A NEW STATION the station banner and diagram bar hide completely — the create page and its ← Back own the screen; no more two-contexts mashup',
      'STALE DRAFTS CAN BE DISCARDED from the "unfinished drafts" banner — each draft chip now has its own × (with confirm); drafts never hijack navigation, they just sit in the list until you resume or discard them',
      'ONE CORRECTIONS BOX — the per-section "change this section" boxes are gone. Say what to change in the single Corrections / Changes box and Jarvis routes it to the right section, leaving everything else exactly as it was; for direct fixes, click any line (sequence steps, recovery steps, device names/purposes, position values) and edit it in place',
      '"STANDARDS USED" MOVED TO THE BOTTOM — it\'s an output of the build (what Jarvis USED), so it now sits at the end of the STATION band next to the derived Inputs & Outputs, same quiet collapsed line. Reference material keeps only what you GIVE Jarvis: the drop zone, thumbnails, and the past-job line',
      '"Code generation notes" is now "LEVEL OF CODE GENERATION" — pick one of three presets (Sequence & fault recovery — proving the logic / Full station — standard build / Full station + machine hooks) that set the build\'s real scope contract, plus the free type/talk line for specifics. Your previously typed text is kept in the free line',
      'CORRECTIONS / CHANGES IS FRONT AND CENTER on a built station\'s sheet — blue accent card, bigger box, primary Apply button: after a build, that box is the main thing you fill out. On a fresh draft it stays quiet',
      'Prose inputs — the generation specifics line, Corrections, the past-job reference line — are capped at a readable width instead of running across the whole monitor',
      'INTERACTIONS "None" IS CLICKABLE — even in a single-station project, click it to note a future or external interaction as free text; with other stations present the station chips work as before. An input is never a dead label',
    ],
  },
  {
    version: 'v2.6.2',
    date: '2026-08-24',
    items: [
      'YOUR SERVO VALUES CAN NEVER BE WIPED AGAIN — re-running "Done explaining" or "Apply changes" now MERGES the new summary into the sheet instead of replacing it: every value you filled stays, new rows add, and nothing you typed vanishes. A sheet linked to a built station also re-loads its committed values from the station itself, so the ServoPNP positions are back automatically',
      'SPEEDS ARE ROWS IN THE POSITIONS TABLE — Fast and Slow sit under the positions with their value boxes aligned in the same column (the cramped side-by-side strip is gone), plus "+ add speed" for extra named speeds that ride into the station',
      'SERVO AXES AND PNEUMATICS SIT SIDE BY SIDE — the device groups are columns across the page when there\'s room, wrapping on smaller screens; cards flow inside each group',
      'ROLE TAGS ARE GONE from servo rows (no more SAFE-CLEAR / TRANSITION / PICK / PLACE chips) — you know what the points are. The amber "✓ agree" proposed rows and red "needed" indicators stay',
      'PAST-JOB REFERENCE IS A TALK/TYPE LINE — say which station, on which job, and what about it (free text, saves with the station) instead of the old name-only box',
      'THE SHEET SPEAKS PLAINLY — bands are "INPUTS" and "STATION — review and correct", "Notes to Jarvis" is now "Code generation notes" (level of detail / intent for the generated code), and the coverage strip is titled "Explanation" so it never reads as contradicting the red blocking bar (they measure different things)',
      'INTERACTIONS with no other stations in the project is just the word "None" — nothing else',
    ],
  },
  {
    version: 'v2.6.1',
    date: '2026-08-24',
    items: [
      'BUILD SCORES ARE OUT OF 100 — every score shows as "N / 100" and the columns say so ("Score /100"). To score: type any number 1-100 (Enter saves) or one-click the 25/50/75/90/100 chips. Existing 1-10 scores were converted (×10); colors: 70+ green, 40+ amber, below 40 red',
    ],
  },
  {
    version: 'v2.6.0',
    date: '2026-08-24',
    items: [
      'THE SHEET IS TWO ZONES — "WHAT YOU GIVE JARVIS" (Reference material, Notes to Jarvis, Interactions — moved up, it\'s initial info you give — and Corrections/Changes) then "THE STATION — review what Jarvis understood" (Devices, Sequence + Fault recovery, IO). Quiet band headers separate them; every section is full page width — the right rail is gone',
      '"WHAT\'S NEEDED" IS A STRIP under the green/red blocking bar — checkmarks fill left-to-right as sections complete, and it GROWS to show everything. STANDING RULE: nothing on the page ever scrolls internally — every panel and list grows until it shows everything',
      'PROPOSED vs NEEDED — unmistakable: Jarvis-proposed servo values are AMBER with an explicit "✓ agree" checkbox per row (checking commits his value, the tag clears); truly-missing values are RED and BOLD with a "needed" tag — never confusable with role tags',
      'DEVICE CARDS: RESPONSIVE GRID — as many narrow cards per row as fit your screen (no dead space on the right); the type-group headers (Servo axes, Pneumatics) span the grid so grouping stays visible',
      'REFERENCE MATERIAL: bigger thumbnails, the drop zone and "Referenced a past job? name it" sit together on the left, and Jarvis\'s citations collapsed behind "Standards used (N)" — expanding to short bullets, never a paragraph',
      'FAULT RECOVERY steps render uniformly — numbered "condition → action" lines, no mixed bold',
      '"Code generation detail" is now "Notes to Jarvis" — one auto-growing line near the top of the input zone',
      'JARVIS MOVED TO THE TOP BAR — a compact square chip (green dot + Jarvis + open-question count) on the top right; the floating bottom-left pill is gone, so it can never sit over your content',
      'The sheet got generous bottom room so the last sections (Inputs & Outputs) can scroll up to the center of your screen',
    ],
  },
  {
    version: 'v2.5.1',
    date: '2026-08-24',
    items: [
      'YOUR CAD PICTURE IS BACK — recovered from the server and restored to the ServoPNP sheet. Root cause of the second loss fixed: saving pictures on the server now only ever ADDS (no state of any tab can overwrite the set), removing one takes your explicit ✕, saves retry on failure, flipping pages FLUSHES the save instead of cancelling it, and every thumbnail wears a live ✓ saved / ⟳ saving badge — a picture can never vanish silently again',
      'DEVICE CARDS: COMPACT, GROUPED BY TYPE — Servo axes and Pneumatics sit in side-by-side columns (table-like), each group labeled and tinted with its device color (servo orange, pneumatic purple); cards are tight with no wasted space and the columns wrap cleanly on smaller screens',
      'THE SHEET READS LIKE AN SDC DATA SHEET — full-width fluid layout (grows with the window), colored section headers in the SDC palette (navy Devices, blue Sequence, green Interactions), and ALL the instructional chrome is gone: no "click any line to edit", no "✓ covered" chips — silence means covered; sections only speak when something is actually needed',
      'FAULT RECOVERY IS THE SECOND SEQUENCE — it sits beside the Main sequence inside the Sequence section as numbered if-then steps (1. any fault → Z to safe height, 2. gripper closed → place…); click a step to edit, + add a step',
      'INTERACTIONS ARE MACHINE-AWARE — chips of the project\'s other stations ("what stations are you interacting with?"); pick one and talk through the interaction right there; it saves with the station. No other stations → just "None"',
      'NEW: "REFERENCE MATERIAL" at the top of the sheet — drop ANYTHING (pictures, .L5X code, PDFs, docs): images feed the extraction, dropped code/docs go straight into Jarvis\'s training intake ("Jarvis studies whatever you drop here"), everything persists with the station and wears the ✓ sync badge. Name a past job ("like the 1119 stamper") right there and Jarvis records it and asks the team to export it',
      'EVERY SERVO POINT ON THE SHEET — blend/wideband anchors the compiled code uses now show as amber "proposed" rows right in the axis card (hover for what the band means); type a value or press Enter to make it a real named position. Redundant role chips (a HOME tag on a row named Home) are gone',
      'Text boxes that take prose now GROW to show everything you write (Code generation detail, Changes, section corrections) — no more one-line scroll. The Changes box has a proper "Corrections / Changes" header. Every toggle app-wide is squared to the SDC chip style, including the Spec Sheet | Diagram pill',
      'Sheet header decluttered: a built station\'s sheet drops the Name/Number inputs (set at creation), the purpose box is a full-width one-line "Code generation detail" row, the redundant page headline is gone, and the corrections box just says "Changes". The right-rail checklist is now "What\'s needed" and only lists actual gaps',
      'Diagram sub-bar: the Sequence | Controls detail toggle is squared to match the SDC chip style, and ✨ Generate is bigger — unmistakably the page\'s primary action',
    ],
  },
  {
    version: 'v2.5.0',
    date: '2026-08-24',
    items: [
      'NEW: PROJECT HOME — the machine overview page. Opening or switching a project lands here: project name + job # (click to edit), a machine summary line, machine notes that save with the project, and one card per station showing where it is in the pipeline (Described → Diagrammed → Compiled → Generated, with the last build\'s label and score). Click a card to open that station\'s Spec Sheet.',
      '"+ ADD STATION" lives on the Project Home as its own card — it opens the describe-first Create Station flow (this answers "where do I add another station?")',
      'A station blocked on open questions shows a RED count badge on its home-page card',
      'The station banner grew a "‹ project" crumb on the left — one click back to the Project Home from any station page. Deep link: /v2.html?page=home',
    ],
  },
  {
    version: 'v2.4.3',
    date: '2026-08-23',
    items: [
      'THE CODE GENERATION PAGE IS GONE — the banner is two pills (Spec Sheet | Diagram); ✨ Generate sits on the Diagram sub-bar right next to Approve, and when a run finishes a compact result card appears in place (label, verdict, ⬇ L5X, score). Past builds live in the Jarvis pill\'s grid.',
      'NO MORE "THIN" BADGES — a spec-sheet section is ✓ covered (judged against what THIS build needs; a standalone station\'s empty interactions counts as covered) or it lists specific needs, each a concrete question with Jarvis\'s proposed answer and a one-click ✓ Agree (free — no re-summarize)',
      'BLOCKING STRIP ALWAYS VISIBLE at the top of the sheet — green "✓ Nothing blocking" at zero, red "Blocking code generation (N)" with every item when something blocks',
      'EVERY SERVO POINT THE CODE USES IS A VISIBLE ROW — the servo table now derives required positions and blend/wideband anchors straight from the compiled sequence: missing ones appear as red rows (proposed value + plain-English meaning, e.g. "Retract blend band — the next move may start once the axis is within 10 mm of Retract"); a move to a position the table doesn\'t know is a genuine blocker',
      'PICTURES PERSIST — anything you paste onto the sheet now also saves on the server with the station: leave, come back, rebuild — still there',
      'ONE DEVICES SECTION — the "Devices I heard" list merged into the device cards (name + purpose editable right on the card header, ✕ to remove, + add a device); Inputs & Outputs demoted to a collapsed derived strip at the bottom; "What can go wrong" is now "Fault recovery"; chips restyled square to match the SDC tools look',
      'NEW: "What\'s this build for?" — optional one-liner near the top of the sheet; it saves with the station and changes how Jarvis approaches the build',
    ],
  },
  {
    version: 'v2.4.2',
    date: '2026-08-23',
    items: [
      'Defaulted servo band values now sit as red proposed rows in the Servo values table (accept by doing nothing, edit by typing), the spec sheet\'s red section is exactly "Blocking code generation (N)", the pneumatic sensor checkboxes work again both directions, and guide-rail concept files are readable & editable on the Jarvis Knowledge tab.',
    ],
  },
  {
    version: 'v2.4.1',
    date: '2026-08-22',
    items: [
      'THE DIAGRAM PAGE IS THE DIAGRAM — the plan panel is gone; one slim row under the banner holds the Sequence | Controls detail toggle, compiled info, and a single small Approve (or Compile) button. Nothing else',
      'TRUE VIEW PARITY — Controls detail now renders the SAME nodes as the Sequence view (the actual node components, same size, same action rows and PT badges) with the stations panel still on the left and the Jarvis pill in its dock; it keeps the clean routing, the recovery lane, and adds part-tracking latch chips',
      'ALL QUESTIONS LIVE ON THE SPEC SHEET — when Jarvis is blocked (paused build questions, defaulted values), the Spec Sheet pill turns RED with a count; open it and every question is there with his proposed solution, answer by talk or type, Continue / Apply-values right there',
      'Key assumptions & Key standards moved to the Jarvis page — on each build\'s expanded row, a few short bullets each (never walls of text), with ✓/✗ on every bullet that teaches Jarvis',
      'Code Generation page split into two clear sections: READY TO GENERATE (pick stations, Generate) and GENERATED (build cards + history) — un-generated stations no longer mix into results',
      'Paused builds on the Code page just point at the Spec Sheet — one home for questions',
    ],
  },
  {
    version: 'v2.4.0',
    date: '2026-08-22',
    items: [
      'FOUR STOPS instead of five — the pill is now Spec Sheet | Diagram | Code Generation. CE Review is gone as a page; everything it held moved to the Diagram page',
      'ONE Diagram page: the clean sequence by default, a Sequence | Controls detail toggle ON THE PAGE flips to the compiled code\'s flowchart — the pill never changes',
      'The controls flowchart\'s nodes now LOOK like the mechanical diagram\'s — same white cards, step badges, device icons, action pills, and the servo POS/SPEED rows — while keeping its clean routing, dotted recovery lines, and the color-coded groupings',
      'Scroll-wheel zoom on the controls flowchart now works exactly like the mechanical canvas — same steps, anchored at the pointer',
      '"How I planned this" — a slim panel on the Diagram page lists Jarvis\'s planning assumptions and the SDC standards each structural choice followed (or the extension it declared), one sentence each, plus the Approve button and the value fill-ins (moved from CE Review). Collapsible; has the Compile button when nothing is compiled yet',
      'Code Generation result cards now show what came up while writing: Jarvis\'s notes ride quietly below the verdict; a STRUCTURAL change he had to make is highlighted amber with an "I agree — approve" button',
      'If Jarvis pauses a build to ask something, the card shows his questions WITH his proposed solutions — leave the answer blank to go with his proposal, then Continue resumes the build',
      '"How Jarvis works" — a new tab on the Jarvis page: six cards walking the whole flow (Spec Sheet → Compile → Approve → Generate → THE CHECK → Delivery), naming what he actually consults at each step, linked to "What Jarvis knows"',
    ],
  },
  {
    version: 'v2.3.0',
    date: '2026-08-22',
    items: [
      'The Controls Diagram is now the real code\'s flowchart — every state, waits, retries, and the recovery path',
      'Every compiled state is drawn with its number, what it commands (moves with position + speed profile, gripper actions, signals), and its exit condition in plain form on the edge (MAM.PC + InPos, wideband OR branches, timer .DN, signal waits) — hover an edge label for the exact rung text',
      'Fault & recovery is its own column: fault 127 → idle 2 → init (Z to retract first), the gripper-state branch (open → return-empty path, closed → carry-to-place path), init complete 124 — with the resume edges showing exactly where the sequence re-enters',
      'Synthesized confirm states (the trigger/wait splits between same-axis segments) are drawn where they actually run, marked "confirm (synthesized)"',
      'Handshakes and part tracking ride along: ⇐/⇒ supervisor chips on the wait and complete states, ⟪PartStarted ↑⟫-style markers on the transitions that latch them, and ⏱ timeout badges (e.g. the hold-and-warn on the next-pick wait)',
      'No compiled sequence yet? The page says so and points at CE Review — it always draws from the latest compile, never a stale copy',
      'The Mechanical Diagram is now ONLY the ME-described sequence: wait nodes (controls furniture like "Wait for Next Pick Signal") are hidden there and the sequence reads straight through — they still live in the station and in the compile',
    ],
  },
  {
    version: 'v2.2.0',
    date: '2026-08-21',
    items: [
      'THE FIVE-PAGE SHELL — one centered, high-contrast pill: Spec Sheet | Mechanical Diagram | Controls Diagram | CE Review | Code Generation. Click through the pages; the pill never moves. (Replaces the view toggles AND the top-right pipeline button/stepper.)',
      'Mechanical Diagram = the sequence as the machine moves: NO state numbers (they\'re a controls concept), part-tracking badges stay visible and read larger',
      'Controls Diagram = the same canvas with the controls layer: state numbers, waits, part tracking',
      'CE Review = the controls engineer\'s page: the compiled-sequence review (moved from Full Controls), the value fill-ins, and this station\'s open questions — answer talk-or-type right there. Optional: nothing blocks without it',
      'Code Generation = one page for the whole machine: pick stations (this one preselected, or Whole machine), answer "do interactions matter?" (saved with the spec), ONE Generate — the live-progress window opens preselected, and results land back on the page: version label, verdict, Download L5X, click-to-score, plus the project\'s generation history',
      'Lanes are implicit: CE-approved stations generate as fast translations, others as full generations — the check runs either way; a note links back to CE Review when approving first would speed things up',
      'All timestamps app-wide are now Eastern, 12-hour — "Aug 21, 3:08 PM", never military time',
      'The code grid has a Label column — v4_SHIP findable by name — next to station, version, cost, score',
      'The bottom-left Jarvis pill is unchanged — the tool-health page: validation, cost, rating, version, how the tool is doing overall',
    ],
  },
  {
    version: 'v2.1.12',
    date: '2026-08-21',
    items: [
      'ONE action button on the whole screen — top right: it always does the next step (Describe → Compile → "Compiling… n%" → Review & approve → Generate → View code) with a step indicator right beside it so you know where you are in the process',
      'Everything else is a page or a review surface: Full Controls lost its Generate button (Re-compile tucked into a quiet ⋯ menu; "Apply values" stays — and when values are outstanding, the top-right button\'s caption says so: "3 values needed"), Build ▾ is gone, and the top-bar Code button merged into the Jarvis page',
      'Jarvis lives in ONE place: the bigger bottom-left Jarvis pill (question-count badge), docked above the PROJECT strip so it never covers anything — his code, questions, knowledge, and track record are all inside',
      'The code grid fits without horizontal scrolling: compact date, project truncates with a tooltip, mode is a one-glyph icon — Jarvis version, duration, cost, and score stay front and center',
      'Score any build right in the grid: click the score cell, click a number 1-10, done — no dialog; click again to change it',
      'Download the L5X right from the grid — a 📄 L5X link on every row, one click to Downloads',
      '"View code" lands you on that station\'s latest build, already expanded',
      'Files ▾ (output folder + legacy exporters) moved into the Jarvis page — file stuff lives with the files',
      'Knowledge tab: "What Jarvis knows and where it came from" — one card per ingested source with its access level, ingest date, and takeaway bullets; amber = a gap he can\'t fully see yet (fills in as the ingestion pipeline catalogs sources)',
      'Normal|Recovery is gone from the banner (unused — the code paths remain if it ever returns)',
    ],
  },
  {
    version: 'v2.1.11',
    date: '2026-08-21',
    items: [
      'THE STATION BANNER — one persistent row above whatever you\'re looking at: S## + name, Normal|Recovery, Spec Sheet|Diagram, Mechanical|Full Controls, the star. The Spec Sheet|Diagram toggle is at the exact same pixels in both views — zero mouse travel to flip back and forth; the view changes beneath it',
      'No more clipped "Normal | Recove" — the crowded floating canvas pill is gone; the banner lays everything out with room, wraps at narrow windows, and never truncates a label',
      'On the Spec Sheet, the diagram-only controls (Normal|Recovery, Mechanical|Full Controls) stay visible but dimmed with the reason — nothing jumps around',
      'ONE code button, always in the banner, always the next step: "⚙ Compile sequence" → "Compiling… n%" → "✓ Review & approve" → "✨ Generate code" (says "ready — instant" when pre-built) → "📄 View code". The bottom bar\'s Generate, the "Generate fast" button, and the Build ▾ compile/generate entries are gone — Build ▾ now holds only the output folder and legacy exports',
      'Jarvis has his own home: a pill in the bottom-left corner with his open-question count — click to open his page. He\'s out of the top bar and out of the code pipeline',
    ],
  },
  {
    version: 'v2.1.10',
    date: '2026-08-21',
    items: [
      'Servo move values never truncate — the POS/SPEED line font auto-shrinks to fit (like the device-name scaler), so "PickTransition — 50.0 mm" is always fully visible; only a very long position NAME can ellipsize, never the number',
      'Blended moves read like Fanuc code: a third aligned END line — "END Blend (InPosWide)" — replaces the little "≈ blends" squiggle; strict moves omit the line entirely',
      'Servo move rows are tighter: smaller value lines, no dead space between lines — noticeably shorter nodes, same readability; tag hints (MAM.PC / InPos) unchanged',
    ],
  },
  {
    version: 'v2.1.9',
    date: '2026-08-21',
    items: [
      'ONE toggle between a station\'s two pages: "Spec Sheet | Diagram" — the same segmented control on both pages, active side highlighted; the "Station Specs" button and "← Back to diagram" are gone (the sheet is first — you toggle, you don\'t go back)',
      'Flips are instant both ways and everything stays put — sheet edits persist through Spec Sheet → Diagram → Spec Sheet',
      'On a not-yet-built draft the Diagram side shows disabled with the reason: build first — the sheet creates the diagram',
      'Sensor checkbox interlock verified live on built-station sheets: checking a sensor grays that direction\'s delay timer, unchecking restores it, and the Inputs list updates (Engaged sensor → i_…Closed). If a sheet ever seems frozen right after an update lands mid-session, one refresh clears it',
    ],
  },
  {
    version: 'v2.1.8',
    date: '2026-08-21',
    items: [
      'State numbering now matches the CE standard — sequences start at 4; 0-3 are SafetyStop/Manual/Idle states',
    ],
  },
  {
    version: 'v2.1.7',
    date: '2026-08-21',
    items: [
      'TRUE two-page flow: the right-side Station Spec card is gone — a "Station Specs" button next to the station header opens the SAME data-sheet page you built from, always as the FULL filled sheet (device cards, servo tables with values, IO lists); "← Back to diagram" returns; edits round-trip losslessly',
      'Stations built before this update get their sheet rebuilt automatically from the station itself (spec, devices, timers, positions, speeds, sequence) — and old leftover drafts for that station are absorbed, so no more "unfinished drafts" banner on a spec visit',
      'A station\'s sheet is its living spec now — it persists after Build, and Build becomes "Rebuild Station": rebuilding REPLACES the station in place instead of adding a duplicate',
      'Servo move rows are readable: axis on top, then aligned "POS — Pick — 60.0 mm" and "SPEED — Slow — 100 mm/s" lines; speed is color-coded (Fast = blue, Slow = amber); nothing spills outside the node border anymore',
      'Generated diagrams never overlap — node spacing is recomputed from real rendered heights (50px gap enforced), at Build time and once more on the canvas',
      'One servo move per state, enforced by rule: a Build can never chain two moves inside one state with "after complete" — the diagram author splits them into chained states (SDC MAM trigger law; blending stays on the connecting edge). Test_Project_v2 ServoPNP was repaired in place',
      'The sideways "PROGRAM PROPERTIES" tab is gone — collapsed properties are a normal horizontal chip at the top right',
    ],
  },
  {
    version: 'v2.1.6',
    date: '2026-08-21',
    items: [
      'Data sheet devices are now real cards — the old app\'s device-card look: colored edge, icon, name over type',
      'Pneumatic sensors are per-direction checkboxes again (like the old device config) — both unchecked = timer only; a direction with a sensor dims its delay timer',
      'Verb naming is per device type everywhere on the sheet: gripper = Engage/Disengage, cylinder = Extend/Retract — labels, delays, sensors, and tags all agree',
      'Servo speeds always come in filled with the SDC standard — Fast 1000 / Slow 100 mm/s, tagged default, editable; you never have to fill speeds',
      'Changes moved where you need them: an "Overall changes" talk/type box at the top of the sheet, plus a slim change box on every section — section edits tell Jarvis exactly which section you mean, and everything applies together',
    ],
  },
  {
    version: 'v2.1.5',
    date: '2026-08-21',
    items: [
      "The review is now the station data sheet — servo points table, pneumatic sensors & timers (speech-fillable, SDC defaults), real input/output lists, and Build tells you exactly what it's waiting for",
      'Servo axes get their named-position table right in the review, pre-filled with the positions Jarvis heard in your sequence — plus a Fast/Slow speeds row; say a value ("pick is at 210") and it lands in the cell',
      'Pneumatics get the old device-config feel: sensor arrangement (SDC default: retract-only), optional stroke, extend/retract delays — stroke-based defaults (under 100mm → 1s, over → 5s, grippers 250ms), each tagged "default" until you say or type otherwise',
      'Inputs & Outputs are now real lists of the actual i_/q_ tags, derived live from the device tables',
      'Build on the data sheet is grayed until ready and always says why — "VerticalAxis: 3 position values needed" — and every reason is a click that takes you to the fix',
      'A question whose answer is a table never shows as prose anymore — the table with its empty cells IS the question; only real judgment questions stay in the Questions block',
    ],
  },
  {
    version: 'v2.1.4',
    date: '2026-08-21',
    items: [
      "Every build now gets Jarvis's own adversarial review against the template before it's marked ready to send — the same pass a senior CE would make: rung ordering, trigger shapes, missing template blocks, style drift",
      'The Code grid shows the verdict on every build: "✓ internal review: ship" or "⚠ internal review: N findings" — open the row for the findings themselves, each with the template evidence',
      'A "fix" verdict never re-runs generation on its own — the build is marked "not ready for external delivery" and a human decides: fix and rebuild, or overrule',
    ],
  },
  {
    version: 'v2.1.3',
    date: '2026-08-21',
    items: [
      'NEW "Code" button in the top bar — the Code page: live pipeline status, answer questions, approve/deny Jarvis\'s decisions, get the file, score it — one grid; badge shows how many builds are running right now',
      'Every station is a row with its live status: servo positions needed / not compiled / compiling (spinner + elapsed) / compiled — awaiting approve / building code / ✓ code ready / failed — honestly',
      'Open a station row: Jarvis\'s open questions with talk-or-type answers, his decisions & assumptions each as one short line with ✓ (good) or ✗ (deny — say why, and the why is filed into his knowledge, attributed to you), then the L5X with the full review block beside it',
      'Work in flight shows in the history grid too: "Generating — Station X (Project Y) — 2:31 elapsed", flipping to the reviewable row on completion',
      'Servo position tables are now a first-class prerequisite: a station missing values shows "⚠ Servo positions needed — VerticalAxis (2 of 5 values)" before compile; compile stays clickable with an honest confirm',
      'The Servo values table — Axis | Position | Value | role tag, editable inline, "+ add named value" per axis (BlendStart/SafeClear become real named positions the generator reads); opened from the warning, the station tree ("Servo values" line), or the flow bar',
      'The "then what?" bar adds a "view code →" link on the Generate stage once a station has builds, and the Generate window\'s finish screen links "See all generated code →"',
      "Full Controls is now the ten-second screen: the summary paragraph, fill-in blanks for the values Jarvis needs, handshakes on one line, Approve — that's it",
      'The "*Verify — needs a real value" flags became literal fill-in inputs (mic on each, full explanation in the tooltip) — type the number, "Apply values" re-compiles with them',
      "Everything long-form — Jarvis's decision notes, mappings, per-state detail — travels with the build instead of cluttering the review screen",
      'Approve now shows what happens next, live: "⚙ Jarvis is building the code in the background" with elapsed time, then "✓ Code is built — Generate is instant" with a Generate button right there; failures show honestly with a Retry',
    ],
  },
  {
    version: 'v2.1.2',
    date: '2026-08-20',
    items: [
      'The Generations grid: download any build, review it (good/bad, talk or text, score), upload the corrected file — Jarvis diffs it and learns',
      'Jarvis page now opens on Generations — every build in one grid: station, project, version, date, duration, cost, validation, mode, score',
      'Open a row: ⬇ Download L5X, "What was good?" / "What was bad?" (mic on both), score 1-10, reviewer name, Save',
      '⬆ Upload corrected version — Jarvis compares it rung-by-rung against his own output, extracts the lessons, and files the confident ones into his concept knowledge (attributed, dated)',
      'Lessons he\'s not sure about go to the Questions queue for the leads to confirm — nothing sketchy lands in his knowledge silently',
      'The row then shows "✓ Corrected version uploaded — Jarvis learned N things (view)" with the lessons and a plain-English summary',
      'Analysis failures are shown honestly ("analysis failed — file kept") and a re-upload retries',
      'Old pre-scoring L5X files on disk appear in the grid too (download-only)',
    ],
  },
  {
    version: 'v2.1.1',
    date: '2026-08-20',
    items: [
      "Build always tells you what it's waiting for (and clicking it takes you there)",
      'Required vs optional is now visually explicit',
      "Questions: no more caps — Jarvis asks what he genuinely needs; 'you decide' is an answer he remembers",
      'Servo move chips now show the speed profile — "→ PickTransition 60.0 · Fast 2500" — so you can see fast-to-here-slow-the-rest right on the canvas; blended corners get a small "≈ blends" hint',
      'Machine tally lines expand — click Valves, Sensors, Inputs, Outputs (IO is now split in/out) or any other line to see exactly which device on which station contributes what',
      'Full Controls now surfaces the open controls questions at the top with talk-or-type answer boxes — "Apply answers" re-compiles with your answers applied and clears the matching queue items',
      'A "then what?" bar at the bottom of the canvas walks the journey: Compile → Review & Approve → Generate, with one button for whatever comes next',
      'Standard vertical spacing is now compact (50px gap) — new stations draw tighter, and the Re-space button applies the same standard to existing ones',
    ],
  },
  {
    version: 'v2.1.0',
    date: '2026-08-20',
    items: [
      'THE BIG ONE — the thinking moved to Build time. Build ▾ → "Compile sequence (Jarvis)": Jarvis reasons through the FULL sequence once (~4 min, well under a dollar) and you review it BEFORE any code exists',
      'Full Controls is real: the compiled sequence renders as a scannable view — every state with its number and actions, every transition with the actual rung condition, waits with their exits, handshakes with set/clear states, and amber "review before approving" flags',
      '"Approve — I agree with this sequence" right on the compiled view — approval is your sign-off, and it flips Generate into translation mode (~2.5 min, ~$0.95 instead of reasoning from scratch)',
      'Change something by explaining it: a talk-or-type notes box under the compiled sequence re-compiles with your notes attached (re-compiling always clears approval so you review again)',
      'Approve and walk away — code pre-builds in the background from your approved sequence; when it\'s ready, Generate shows "✓ code built — instant" and Start is an immediate download',
      'The Generate picker now tags each station: "approved → translation" (fast path) or "✓ code built — instant"',
      'No compiled sequence yet? Full Controls says so honestly and offers the Compile button right there',
      'Under the hood, today\'s batch: R02 rungs carry a state-map comment (readable in Studio 5000), generated comments are validated, stations can be addressed by name, and translation-mode numbers are live from real builds',
    ],
  },
  {
    version: 'v2.0.6',
    date: '2026-08-20',
    items: [
      'Generate now asks what you\'re generating — tiers: station sequence (pick one or several), multi-station integration (early), full machine (coming)',
      'Pick several stations and Jarvis generates each in turn — "Station 2 of 3" progress, one L5X per station, a score row for every build',
      'Cancel mid-run stops after the in-flight station and reports which ones completed',
      'No more "is it frozen?" — you now WATCH Jarvis think: live reasoning summaries stream into the log while it works, with a pulsing alive dot',
      'The ring moves honestly through the thinking phase (15→45%) and holds rather than fakes when reasoning runs long; when writing starts the status flips to "Writing the edit plan — N tokens" (45→70%)',
      'Typical-duration hint under the timer (from Jarvis\'s own build history), and an amber "connection may be stalled" warning only if the stream truly goes silent for 90+ seconds (the server now heartbeats every 15s)',
      'Dead stream mid-run? One-click "Retry generation" re-runs the station on a fresh connection; Cancel becomes "Cancel & clean up"',
      'Tree counts drop the ~ (looked like negative numbers)',
      'App-wide UI scaling control (−/100%/+ in the top bar), like the other SDC Tools apps',
    ],
  },
  {
    version: 'v2.0.5',
    date: '2026-08-20',
    items: [
      'Feature tree left panel — the same tree as the estimate builder: caret + colored square + name + dotted leader + right-aligned count on every row',
      'Tree levels: Machine root (name + job #) → Machine totals (the quoting tally) → Stations (each expands to its Spec line + devices; drafts listed too) → Documents',
      'Station squares tell you the state at a glance: amber = no spec yet, green ✓ = spec + logic drawn, red = last Jarvis build failed validation',
      'Quiet "incomplete: N no spec" badge on the machine root — never a popup',
      'The tree drives the canvas: click a station to show it; selecting a station anywhere auto-expands its tree node',
      'FIXED: scroll-wheel zoom dying after a project switch (the canvas briefly unmounts and lost its wheel listener) — zoom now survives project switches in both apps',
      'Station Spec: answer Jarvis\'s clarifying questions right in the banner — type or talk, then "Apply answers" folds them into the spec',
      'Answered questions disappear; Jarvis never re-asks a question you already answered, even reworded',
      'Saving a spec with open questions sends them to Jarvis\'s queue for the controls team (noted in the banner)',
    ],
  },
  {
    version: 'v2.0.4',
    date: '2026-08-20',
    items: [
      'After Build, you land on the canvas — no second review layer; open questions go to Jarvis\'s queue',
      'Summary is editable in place — click any line to change it, no edit buttons; "+ add a line" per section',
      'Edited the summary? A sticky bar offers "Resubmit to Jarvis" (re-checks with your edits) or "keep my edits as-is"',
      'Non-standard detection — when a request contradicts an SDC standard, an amber "Not SDC standard" card shows what you asked vs the standard; Jarvis builds it your way and flags it for controls review (saved with the station)',
      '+ New Station always starts blank — no more silent draft restore',
      'Unfinished drafts are listed per project: a banner on the fresh page and a "Drafts (N)" row in the Stations panel (resume with one click, discard with ✕)',
    ],
  },
  {
    version: 'v2.0.3',
    date: '2026-08-20',
    items: [
      'FIXED the recurring "server offline" / "Diagram request failed (500)" — the API server was dying whenever its launcher shell closed; it now runs as a detached process',
      'Build Station always clickable — the dead "Build as-is" path is gone; thin coverage = one confirm, then it builds',
      'Project lifecycle: close tabs → clean-slate start screen → ＋ New Project (name + job #) → stations inside',
      'Project delete actually deletes (fixed the save-on-switch resurrection bug); New Project + delete in the picker',
      'Stations panel: old-app device rows (icons + full names), expandable per station',
      'Machine totals (quoting estimate): servos, motors, pneumatics, ~valves, sensors, vision, ~IO — live',
      'View switcher merged into the station pill — no more overlapping headers',
      'Per-project Documents drawer (drag/paste/browse) for release docs Jarvis will read',
      'Summary cards: status chips in headers, device icons, IO & Pneumatics capture',
      'Build scoring: every build auto-recorded; score it 1-10 with a dictated comment; avg per version in Track record',
      'Mic on every text input (answers, comments, edits) — talk anywhere you can type',
      'Jarvis knowledge grouped by topic (servo PnP, pneumatics, recovery…) and editable per line',
      'Dev server now opens /v2.html, and v2 never navigates you back to the classic app',
    ],
  },
  {
    version: 'v2.0.2',
    date: '2026-08-19',
    items: [
      'Questions never block Build — Jarvis decides open ones per SDC standards and notes them for review',
      'No more question loops: max 3 per round, zero new questions after round two',
      '"Build as-is" escape hatch even when coverage is thin (Jarvis fills gaps and flags them)',
      'Device taxonomy fixed — valves and "EOAT assemblies" are no longer listed as devices',
      'Jarvis standing knowledge: standard-answer questions (servo speeds in HMI, timers…) are never asked',
      'Jarvis learns from your answers — standing rules are remembered permanently ("won’t ask again")',
      'The Jarvis page (v2 shell, top bar): question queue for the controls team, knowledge browser, track record',
      'This version badge — hard reset button, latest changes, and what’s still being built',
    ],
  },
  {
    version: 'v2.0.1',
    date: '2026-08-19',
    items: [
      'Describe-first Create Station — just talk; a live checklist fills in and gates the Build button',
      'Voice dictation with the checklist reacting live as you speak',
      'Create flow is now a full page with draft autosave — nothing is lost if you close it',
      'Ctrl+V pastes screenshots straight into the description',
      'Jarvis summary shown as scannable section cards, with its Questions called out',
      'Real progress rings while Jarvis works (no more fake spinners)',
      'Cost ceilings replace token limits — $5 for a summary, $20 for a generate',
      'New v2 shell: stations list on the left, view switcher, Build menu',
      'In-app project picker — open and switch projects without leaving the app',
      'Decision-node handle fix — branches connect from the correct side',
    ],
  },
];

// Being built right now — NOT in the current installed build yet.
export const IN_PROGRESS = [
  'Background pre-build service — the "instant Generate" backend piece (the UI is ready and lights up when it lands)',
  'Compiled sequence rendered as real nodes on the canvas (today it\'s the structured list view)',
  'Jarvis brain moves to the shared SDC AppStack database — one Jarvis for the whole team',
];
