/**
 * retryTargets.js — v3: RETRY IS CONFIGURED, NOT DRAWN (Dan, 2026-09-02).
 *
 * On a Check node the ME ticks Retry and picks WHICH EARLIER STEP to go back
 * to; the retry loop edge DRAWS ITSELF (exit-retry → that step, the v1
 * U-route per the routing laws). The count defaults to the SDC standard (3)
 * and is overridable in the node's popup. Retry exhausted → the machine runs
 * INITIALIZATION (the init block) — implicit, generated by codegen from the
 * check's retry config; nothing is drawn for it.
 *
 * This module is the ONE place that knows the self-drawn edge:
 *   - listRetryTargets(sm, nodeId)  → the dropdown of steps to go back to
 *   - syncRetryLoopEdge(store, smId, nodeId, cfg) → upsert / remove the edge
 *     (`data.autoRetryLoop: true` marks it as ours)
 */

import { computeStateNumbers } from '../lib/computeStateNumbers.js';

/** Short human label for a node in the "go back to" dropdown. */
export function stepLabel(node, sm) {
  const d = node?.data ?? {};
  if (d.isInitial) return 'Home';
  if (d.isComplete) return 'Cycle Complete';
  if (node.type === 'decisionNode') {
    const what = d.signalName || d.label || 'signal';
    return `${d.nodeMode === 'verify' ? 'Check' : d.nodeMode === 'decide' ? 'Decide' : 'Wait'}: ${what}`;
  }
  const acts = d.actions ?? [];
  if (acts.length) {
    const a = acts[0];
    if (a.pickerV2) return `${a.pickerConfig?.mode === 'action' ? (a.pickerConfig?.actionVerb ?? 'Action') : 'Check'} ${a.pickerConfig?.subjectName ?? ''}`.trim();
    if (a.deviceId === '_decision') return `${a.nodeMode === 'verify' ? 'Check' : a.nodeMode === 'decide' ? 'Decide' : 'Wait'}: ${a.signalName ?? ''}`.trim();
    const dev = (sm?.devices ?? []).find((x) => x.id === a.deviceId);
    const more = acts.length > 1 ? ` +${acts.length - 1}` : '';
    return `${a.operation ?? ''} ${dev?.displayName ?? dev?.name ?? ''}`.trim() + more;
  }
  return d.label || node.id;
}

/**
 * The steps a Check can retry back to. Upstream steps (ancestors on the
 * drawn flow, nearest first) come first; every other step follows under
 * `group: 'other'` so a redo step drawn beside the main line is still
 * pickable. Excludes the check itself and Cycle Complete.
 * @returns {{ id, label, step, group: 'upstream'|'other' }[]}
 */
export function listRetryTargets(sm, nodeId) {
  const nodes = sm?.nodes ?? [];
  const edges = sm?.edges ?? [];
  const { stateMap } = computeStateNumbers(nodes, edges, sm?.devices);
  const inBy = new Map();
  for (const e of edges) (inBy.get(e.target) ?? inBy.set(e.target, []).get(e.target)).push(e.source);
  const upstream = new Set();
  const stack = [nodeId];
  while (stack.length) {
    const id = stack.pop();
    for (const src of inBy.get(id) ?? []) {
      if (src === nodeId || upstream.has(src)) continue;
      upstream.add(src);
      stack.push(src);
    }
  }
  const row = (n, group) => ({ id: n.id, label: stepLabel(n, sm), step: stateMap.get(n.id) ?? null, group });
  const ups = nodes.filter((n) => upstream.has(n.id) && !n.data?.isComplete)
    .map((n) => row(n, 'upstream'))
    .sort((a, b) => (b.step ?? -1) - (a.step ?? -1)); // nearest (highest step) first
  const others = nodes.filter((n) => !upstream.has(n.id) && n.id !== nodeId && !n.data?.isComplete)
    .map((n) => row(n, 'other'))
    .sort((a, b) => (a.step ?? 1e9) - (b.step ?? 1e9));
  return [...ups, ...others];
}

/** The edge data every self-drawn retry loop carries. */
export function retryLoopEdgeData(extra = {}) {
  return {
    conditionType: 'custom', label: 'Retry', outcomeLabel: 'Retry',
    isDecisionExit: true, exitColor: 'retry', autoRetryLoop: true,
    ...extra,
  };
}

/**
 * Make the drawn graph match the check's retry config: exactly one
 * exit-retry edge to `retryTargetNodeId` when retry is on, none when off.
 * A hand-drawn exit-retry edge (no autoRetryLoop flag) is retargeted rather
 * than duplicated. Uses store actions so undo/redo and recovery routing work.
 */
export function syncRetryLoopEdge(store, smId, nodeId, { retryEnabled, retryTargetNodeId }) {
  const sm = store.project?.stateMachines?.find((s) => s.id === smId);
  if (!sm) return;
  const edges = sm.edges ?? [];
  const existing = edges.filter((e) => e.source === nodeId && e.sourceHandle === 'exit-retry');
  const target = retryEnabled && retryTargetNodeId ? (sm.nodes ?? []).find((n) => n.id === retryTargetNodeId) : null;
  if (!target) {
    for (const e of existing) if (e.data?.autoRetryLoop) store.deleteEdge(smId, e.id);
    return;
  }
  const keep = existing.find((e) => e.target === target.id);
  for (const e of existing) if (e !== keep) store.deleteEdge(smId, e.id);
  if (keep) return;
  store.addEdge(smId, {
    source: nodeId, sourceHandle: 'exit-retry',
    target: target.id, targetHandle: target.type === 'decisionNode' ? 'input' : null,
  }, retryLoopEdgeData());
}
